import {L, language, setLanguage, eventText} from './i18n.js';
import {Game,distance,W,H} from './engine.js';
import {World} from './world.js';
import {head,techPanel,policyPanel,cityPanel,diplomacyPanel,empirePanel,improvePanel,faithPanel,greatPanel,promotePanel,helpPanel,menuPanel,victoryPanel} from './panels.js';
import {AmbientSound} from './sound.js';
import {icon} from './icons.js';
import {TERRAIN,RESOURCES,TECHS,TECH,ERAS,UNITS,BUILDINGS,WONDERS,POLICIES,POLICY,IMPROVEMENTS,FACTIONS,VERSION} from './data.js';
const $=s=>document.querySelector(s),I=icon;
setLanguage(localStorage.getItem('hellas-language') === 'en' ? 'en' : 'zh');
const stored=localStorage.getItem('hellas-autosave');
export let game=stored?new Game(JSON.parse(stored)):new Game();
const ambient=new AmbientSound();
let selected=game.s.units.find(u=>u.owner==='greece'&&!UNITS[u.type].civilian)?.id,world,modalView=null,modalArg=null,productionTab='unit',busy=false,sound=false;
const button=(action,label,ico='',cls='',extra='')=>`<button class="action ${cls}" data-action="${action}" ${extra}>${ico?I(ico):''}${label}</button>`;
export function toast(msg){$('#toast').textContent=eventText(msg);$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),3600);}
function run(fn){const result=fn();if(result===false&&game.error){toast(game.error);game.error=null;}return result;}
function save(auto=true){localStorage.setItem(auto?'hellas-autosave':'hellas-save',game.serialize());if(!auto)toast(L("游戏已保存到此浏览器。"));}
function turnYear(){const year=-4000+(game.s.turn-1)*40;return year<0?L("公元前 {{v0}} 年", {v0:-year}):L("公元 {{v0}} 年", {v0:year||1});}
function staticText(){
 document.documentElement.lang=language==='zh'?'zh-CN':'en';
 document.title=L('HELLAS · 希腊文明');
 $('#game').setAttribute('aria-label',L('希腊文明策略游戏'));
 document.querySelector('meta[name="description"]').content=L('率领亚历山大的希腊，在3D六角地图上探索、建城、研究科技、制定政策，与城邦结盟并争夺文明的未来。');
 $('#turn-curtain b').textContent=L('历史正在书写');
 $('#turn-curtain small').textContent=L('其他势力的回合');
 $('.map-hint').innerHTML=L('拖动平移 · 滚轮缩放 · 右键旋转')+' <span>'+L('点击单位，再点击蓝色地块移动')+'</span>';
}
function header(){const s=game.s,y=game.yields();const stat=(ic,name,val,rate,cl,action)=>`<button class="resource ${cl}" data-action="${action}" title="${name}"><span>${I(ic)}</span><div><strong>${Math.floor(val)}</strong>${rate!==null?`<span class="rate">${rate>=0?'+':''}${rate}</span>`:''}<small>${name}</small></div></button>`;$('#topbar').innerHTML=`<button class="brand" data-action="home" title="${L("返回首都")}">${I('laurel')}<span><strong>HELLAS</strong><small>${L("希腊 · 文明的曙光")}</small></span></button><div class="resources">${stat('coin',L("国库"),s.gold,y.gold,'gold','empire')}${stat('flask',L("科研"),y.science,null,'blue','tech')}${stat('scroll',L("文化"),s.culture,y.culture,'purple','policy')}${stat('star',L("信仰"),s.faith,y.faith,'gold','faith')}${stat('smile',L("幸福度"),y.happiness,null,y.happiness<0?'red':'green','empire')}</div><div class="top-right"><button class="language-switch" data-action="language" aria-label="${language==='zh'?'Switch to English':'切换为中文'}" title="${language==='zh'?'Switch to English':'切换为中文'}"><span class="${language==='zh'?'active':''}">中</span><i>/</i><span class="${language==='en'?'active':''}">EN</span></button><button class="date" data-action="empire"><strong>${turnYear()}</strong><small>${L("第 {{v0}} 回合",{v0:s.turn})} · ${L(ERAS[game.era()])}</small></button><button class="icon-btn" data-action="help" title="${L("游戏指南 [H]")}">${I('help')}</button><button class="icon-btn" data-action="menu" title="${L("游戏菜单 [Esc]")}">${I('menu')}</button></div>`;}
function sides(){const s=game.s,y=game.yields(),t=TECH[s.research];$('#left-panel').innerHTML=`<button class="panel research-card" data-action="tech"><div class="eyebrow"><span>${L("RESEARCH · 科技研究")}</span>${I('tree')}</div><div class="research-main"><div class="medallion">${I(t?.icon||'flask')}</div><div><h2>${L(t?.name)||L("选择科技")}</h2><p>${t?L("{{v0}} · 还需 {{v1}} 回合", {v0:L(ERAS[t.era]),v1:Math.max(1,Math.ceil((t.cost-s.science)/y.science))}):L("新的知识正等待探索")}</p></div></div><div class="progress blue"><span style="width:${t?s.science/t.cost*100:0}%"></span></div><div class="card-bottom"><span>${t?L("{{v0}} / {{v1}} 科研", {v0:Math.floor(s.science),v1:t.cost}):L("已掌握 {{v0}} 项科技", {v0:s.techs.length})}</span><span>${L("科技树 ")}${I('chevron')}</span></div></button><button class="panel policy-card ${s.culture>=game.policyCost()?'ready':''}" data-action="policy">${I('scroll')}<div><strong>${s.culture>=game.policyCost()?L("可采纳新政策"):L("社会政策")}</strong><div class="progress purple"><span style="width:${s.culture/game.policyCost()*100}%"></span></div><small>${Math.floor(s.culture)} / ${game.policyCost()}${L(" 文化")}</small></div>${I('chevron','chev')}</button><div class="objectives"><div class="section-label">${L("时代的足迹")}</div>${[[s.techs.length>=4,L("探索与求知"),L("研究 4 项科技，开启文明之路")],[game.owned().length>=2,L("扩张希腊的疆域"),L("训练移民，建立第二座城市")],[Object.values(s.influence).some(v=>v>=60),L("缔结希腊同盟"),L("与至少一个城邦成为盟友")]].map(([done,a,b])=>`<div class="objective ${done?'done':''}">${I(done?'check':'compass')}<div>${a}<small>${b}</small></div></div>`).join('')}</div><div class="turn-log">${s.log.slice(0,2).map(e=>`<div class="event-line">${I(e.type==='war'?'sword':e.type==='science'?'flask':'scroll',e.type==='war'?'red':'gold')}<span>${eventText(e.text)}</span></div>`).join('')}</div>`;$('#right-panel').innerHTML=`<div class="panel leader"><div class="leader-title">${I('laurel')}<div><h2>${L("亚历山大")}</h2><small>ALEXANDER · GREECE</small></div></div><div class="leader-ability"><div class="eyebrow">${L("希腊同盟")}</div><p>${L("城邦影响力衰减速度减半，恢复速度加倍。让友谊成为帝国的力量。")}</p><div class="pair"><span class="trait">${I('shield')}${L("重装步兵")}</span><span class="trait">${I('horse')}${L("伙伴骑兵")}</span></div></div></div><div class="nav-row"><button class="nav-card" data-action="empire">${I('columns')}${L("帝国总览")}</button><button class="nav-card" data-action="diplomacy">${I('handshake')}${L("城邦外交")}</button></div><div class="diplomacy-strip">${Object.entries(FACTIONS).filter(([k])=>!['greece','barbarian'].includes(k)).map(([id,f])=>`<button class="faction-disc ${game.isWar(id)?'war':''}" style="--faction:${f.color}" data-action="diplomacy" title="${L(f.name)} · ${game.isWar(id)?L("战争"):s.influence[id]>=60?L("盟友"):L("和平")}">${I(f.icon)}</button>`).join('')}</div>`;}
function selection(){const u=game.unit(selected);if(!u){$('#selection').innerHTML=`<div class="panel empty-selection">${I('compass')}<span>${L("选择单位，探索你的世界。")}</span></div>`;return;}const d=UNITS[u.type],t=game.at(u.tile),owned=u.owner==='greece';const stat=(ic,v,n)=>`<div class="unit-stat">${I(ic)}<div><strong>${v}</strong><small>${n}</small></div></div>`;let actions='';if(owned){if(u.type==='settler')actions+=button('found',L("建立城市"),'columns','primary');if(u.type==='worker'){actions+=button('improve',L("改良地块"),'hammer','primary');}if(u.sleep)actions+=button('wake',L("唤醒"),'sun');else{actions+=button('fortify',d.civilian?L("驻留"):L("驻扎恢复"),'shield');actions+=button('skip',L("跳过"),'arrow');}if(d.upgrade&&game.has(UNITS[d.upgrade].tech))actions+=button('upgrade',L("升级"),'plus');if(u.xp>=15*(u.promotions.length+1))actions+=button('promote',L("晋升"),'star','primary');actions+=button('nextunit',L("下一单位"),'chevron');}
$('#selection').innerHTML=`<div class="panel unit-panel"><div class="unit-heading"><div class="medallion">${I(d.icon)}</div><div><small>${d.unique?L("希腊特色单位"):L(FACTIONS[u.owner].name)+' · '+(d.civilian?L("平民单位"):d.ranged?L("远程单位"):d.mounted?L("骑兵单位"):L("陆军单位"))}</small><h2>${L(d.name)}</h2></div><button class="close-selection" data-action="deselect" title="${L("取消选择")}">${I('close')}</button></div><div class="unit-stats">${stat('sword',d.ranged||Math.round(game.strength(u)),d.ranged?L("远程战力"):L("战斗力"))}${stat('route',`${u.moves}/${d.moves}`,L("移动力"))}${stat('heal',`${u.hp}/100`,L("生命值"))}</div><div class="unit-actions">${actions}</div>${owned?`<div class="movement-legend"><span><i class="move"></i>${L("可移动")}</span><span><i class="current"></i>${L("已选单位")}</span><span><i class="attack"></i>${L("攻击目标")}</span></div>`:''}<p class="unit-tip">${u.job?L("正在建造{{v0}} · 剩余 {{v1}} 回合", {v0:L(IMPROVEMENTS[u.job.kind].name),v1:u.job.left}):u.sleep?L("部队已驻扎。新回合可唤醒并移动，防守反击不消耗你的行动。"):owned?u.moves>0?L("点击蓝色地块移动，点击射程内敌军攻击。"):L("本回合行动已完成，结束回合后恢复。"):L("{{v0}} · 地形防御 +{{v1}}%", {v0:L(TERRAIN[t.terrain].name),v1:(TERRAIN[t.terrain].defense||0)*100})}${u.xp?L(" · {{v0}} 经验", {v0:u.xp}):''}</p></div>`;}
function turnPanel(){const s=game.s,active=s.units.filter(u=>u.owner==='greece'&&u.moves>0&&!u.sleep).length;$('#turn-panel').innerHTML=`<div class="minimap-wrap"><canvas id="minimap" width="260" height="140" aria-label="${L("世界缩略地图")}"></canvas><div class="minimap-footer"><span>${L("地中海 · 标准世界")}</span><span>${Math.round(s.tiles.filter(t=>t.explored).length/s.tiles.length*100)}${L("% 已探索")}</span></div></div><button class="end-turn" data-action="endturn" ${busy?'disabled':''}><div><strong>${s.victory?L("历史终章"):L("下一回合")}</strong><small>${s.victory?'VIEW LEGACY':'END TURN'} · ${s.turn}</small></div>${I(s.victory?'trophy':'arrow')}</button><div class="turn-notice">${active>0?L("{{v0}} 支部队等待指令", {v0:active}):L("所有部队已完成行动")} <span>· Enter</span></div>`;$('#minimap').onclick=e=>{const r=e.target.getBoundingClientRect();const c=Math.floor((e.clientX-r.left)/r.width*W),row=Math.floor((e.clientY-r.top)/r.height*H);world.focus(Math.min(H-1,row)*W+Math.min(W-1,c));};}
function controls(){$('#map-tools').innerHTML=[['home','compass',L("返回雅典 [Home]")],['zoomIn','plus',L("放大")],['zoomOut','minus',L("缩小")],['rotate','globe',L("旋转视角 [Q / E]")],['grid','grid',L("六角网格 [G]")]].map(([a,i,t])=>`<button class="map-btn" data-action="${a}" title="${t}">${I(i)}</button>`).join('');}
function render(){staticText();header();sides();selection();turnPanel();if(world){world.update();world.select(selected);}if(modalView)renderModal();save();}
function selectUnit(id,focus=false){selected=id;selection();world.select(id);if(focus){const u=game.unit(id);if(u)world.focus(u.tile);}}
function tileClick(t,hint={}){if(busy||!t.explored)return;if(hint.city){openModal('city',hint.city);return;}if(hint.unit){const target=game.unit(hint.unit);if(target?.owner==='greece'||!selected){selectUnit(hint.unit);return;}}
const u=game.unit(selected),target=game.unitsAt(t.id).find(v=>v.owner==='greece');if(target&&(!u||u.tile!==t.id)){selectUnit(target.id);return;}if(u&&u.owner==='greece'&&u.tile!==t.id){run(()=>game.move(u.id,t.id));return;}const c=game.cityAt(t.id);if(c){openModal('city',c.id);return;}if(target)selectUnit(target.id);}
function tileHover(t,x=0,y=0){const el=$('#tile-tooltip');if(!t||!t.explored||$('#modal').open){el.style.display='none';return;}const yields=game.tileYield(t),r=RESOURCES[t.resource],u=game.unit(selected),foe=game.unitsAt(t.id).find(v=>v.owner!=='greece'&&t.visible);let battle='';if(u&&u.owner==='greece'&&foe&&game.isWar(foe.owner)&&distance(game.at(u.tile),t)<=(UNITS[u.type].range||1)){const p=game.combatPreview(u,foe);battle=`<div class="battle-preview">${L("攻击 ")}${L(UNITS[foe.type].name)}<br>${L("预计造成 ")}${p.dealt}${L(" 伤害 · 承受 ")}${p.received}${L(" 伤害")}</div>`;}
el.innerHTML=`<strong>${L(TERRAIN[t.terrain].name)}${r&&(!r.tech||game.has(r.tech))?' · '+L(r.name):''}</strong><span class="muted">${t.owner?' · '+L(FACTIONS[t.owner].name):''}</span><div class="tile-yields">${Object.entries(yields).filter(([,n])=>n>0).map(([k,n])=>`<span class="${k==='food'?'green':'gold'}">${I(k==='food'?'wheat':k==='production'?'hammer':'coin')}${n}</span>`).join('')}</div>${t.improvement?`<div class="muted">${L(IMPROVEMENTS[t.improvement].name)}${t.road?L(" · 道路"):''}</div>`:''}${t.ruin?`<div class="gold">${L("古代遗迹 · 派单位前往探索")}</div>`:''}${t.camp?`<div class="red">${L("野蛮人营地")}</div>`:''}${battle}${u&&u.owner==='greece'&&world.reachable.has(t.id)&&t.id!==u.tile?`<div class="movement-preview">${L('移动消耗 {{v0}} · 剩余 {{v1}}',{v0:world.reachableCosts.get(t.id),v1:u.moves-world.reachableCosts.get(t.id)})}</div>`:''}`;el.style.left=Math.min(x+18,innerWidth-270)+'px';el.style.top=Math.min(y+18,innerHeight-150)+'px';el.style.display='block';}
async function nextTurn(){
 if(busy)return;
 if(game.s.victory){openModal('victory');return;}
 busy=true;
 $('#game').inert=true;
 $('#game').setAttribute('aria-busy','true');
 $('.end-turn').disabled=true;
 $('#turn-curtain').classList.add('show');
 try {
  await new Promise(resolve=>setTimeout(resolve,380));
  game.endTurn();
  if(!game.unit(selected))selected=game.s.units.find(u=>u.owner==='greece')?.id;
  selection();world.select(selected);
 } finally {
  busy=false;
  $('#game').inert=false;
  $('#game').setAttribute('aria-busy','false');
  $('#turn-curtain').classList.remove('show');
  $('.end-turn').disabled=false;
 }
 if(game.s.victory)openModal('victory');
 else if(!game.s.research)toast(L('研究完成！点击左上角选择下一项科技。'));
 else if(game.s.culture>=game.policyCost())toast(L('文化积累已足够，可以采纳一项新政策。'));
}
function openModal(view,arg=null){const changed=modalView!==view;modalView=view;modalArg=arg;renderModal();if(changed)$('#modal').scrollTop=0;if(!$('#modal').open)$('#modal').showModal();$('#tile-tooltip').style.display='none';}
function closeModal(){modalView=null;modalArg=null;$('#modal').close();}
function modalHead(title,en,sub=''){return `<div class="modal-head"><div><div class="eyebrow">${en}</div><h1>${title}</h1>${sub?`<div class="modal-sub">${sub}</div>`:''}</div><button class="close" data-action="close" aria-label="${L("关闭")}">${I('close')}</button></div>`;}
function renderModal(){
const scroll=$('#tech-scroll'),sx=scroll?.scrollLeft||0,sy=scroll?.scrollTop||0,bodyScroll=$('#modal').scrollTop;
let html='';switch(modalView){
case'tech':html=techPanel(game);break;case'policy':html=policyPanel(game);break;case'city':html=cityPanel(game,modalArg,productionTab);break;case'diplomacy':html=diplomacyPanel(game);break;case'empire':html=empirePanel(game);break;case'help':html=helpPanel();break;case'menu':html=menuPanel(!!localStorage.getItem('hellas-save'),sound);break;case'faith':html=faithPanel(game);break;case'greatpeople':html=greatPanel(game);break;case'improve':html=improvePanel(game,selected);break;case'promote':html=promotePanel(game,selected);break;case'victory':html=victoryPanel(game);break;
case'confirmwar':html=head(L("宣战"),'A MOMENT OF DECISION')+`<div class="modal-body confirm-box"><h2>${L("向{{v0}}宣战？",{v0:L(FACTIONS[modalArg].name)})}</h2><p>${L("双方将进入战争状态，现有商路会中断，城邦影响力降至 −60。军队可以进入对方领土并发动攻击。")}</p><div class="confirm-actions">${button('diplomacyact',L("宣战"),'sword','danger',`data-owner="${modalArg}" data-kind="war"`)}${button('diplomacy',L("返回外交"),'handshake')}</div></div>`;break;
case'newgame':html=head(L("开启新的文明"),'A NEW BEGINNING')+`<div class="modal-body confirm-box"><h2>${L("重新书写希腊的历史")}</h2><p>${L("开始新游戏会覆盖自动存档。你可以先在菜单中手动保存，或导出当前进度。")}</p><div class="confirm-actions">${button('restart',L("开始新游戏"),'globe','primary')}${button('menu',L("返回菜单"),'arrow')}</div></div>`;break;
case'loadconfirm':html=head(L("读取存档"),'RETURN TO HISTORY')+`<div class="modal-body confirm-box"><p>${L("读取手动存档将替换当前游戏进度。")}</p><div class="confirm-actions">${button('loadnow',L("读取存档"),'load','primary')}${button('menu',L("返回菜单"),'arrow')}</div></div>`;break;
}
$('#modal-content').innerHTML=html;$('#modal').scrollTop=bodyScroll;if($('#tech-scroll')){$('#tech-scroll').scrollLeft=sx;$('#tech-scroll').scrollTop=sy;}
if($('#import-file'))$('#import-file').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const parsed=JSON.parse(await f.text());validateSave(parsed);localStorage.setItem('hellas-autosave',JSON.stringify(parsed));location.reload();}catch(err){toast(L("无法导入：")+err.message);}};
}
function validateSave(s){if(s.version!==VERSION||!Array.isArray(s.tiles)||s.tiles.length!==W*H||!Array.isArray(s.cities)||!Array.isArray(s.units)||!Array.isArray(s.techs)||!Array.isArray(s.policies)||!s.log||!s.influence||!Number.isFinite(s.turn)||!Number.isFinite(s.gold))throw Error(L("文件不是本游戏的有效存档。"));if(s.techs.some(t=>!TECH[t])||s.policies.some(p=>!POLICY[p])||s.units.some(u=>!UNITS[u.type]||!FACTIONS[u.owner]||!s.tiles[u.tile])||s.tiles.some(t=>!TERRAIN[t.terrain])||s.cities.some(c=>!FACTIONS[c.owner]||!s.tiles[c.tile]||/[<>]/.test(L(c.name)))||s.log.some(e=>typeof e.text!=='string'||/[<>]/.test(e.text)))throw Error(L("存档内容不完整或包含无效数据。"));}
function exportSave(){const blob=new Blob([game.serialize()],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`Hellas-turn-${game.s.turn}.json`;a.click();URL.revokeObjectURL(url);toast(L("存档文件已导出。"));}
function handleAction(a,el){if(busy)return;switch(a){
case'language':setLanguage(language==='zh'?'en':'zh');localStorage.setItem('hellas-language',language);$('#toast').classList.remove('show');$('#toast').textContent='';$('#tile-tooltip').style.display='none';controls();render();break;
case'research':if(run(()=>game.research(el.dataset.id)))toast(L("开始研究：")+L(TECH[el.dataset.id].name));break;
case'adopt':if(run(()=>game.adopt(el.dataset.id)))toast(L("已采纳：")+L(POLICY[el.dataset.id].name));break;
case'opencity':productionTab='unit';openModal('city',Number(el.dataset.id));world.focus(game.city(Number(el.dataset.id)).tile);break;
case'productiontab':productionTab=el.dataset.tab;renderModal();break;
case'produce':case'buy':if(run(()=>game.production(game.city(Number(el.dataset.city)),el.dataset.kind,el.dataset.id,a==='buy')))toast(a==='buy'?L("购买完成。"):L("已安排城市生产。"));break;
case'cityfocus':run(()=>game.focusCity(Number(el.dataset.city),el.dataset.focus));break;
case'buytile':run(()=>game.buyTile(Number(el.dataset.city),Number(el.dataset.tile)));break;
case'bombard':run(()=>game.bombard(Number(el.dataset.city),Number(el.dataset.id)));break;
case'attackcity':if(selected&&run(()=>game.move(selected,game.city(Number(el.dataset.id)).tile)))closeModal();else if(!selected)toast(L("请先选择一支军队。"));break;
case'diplomacyact':{const ok=run(()=>game.diplomacy(el.dataset.owner,el.dataset.kind));if(ok){modalView='diplomacy';modalArg=null;renderModal();toast(el.dataset.kind==='war'?L("战争开始。"):L("外交行动已完成。"));}break;}
case'confirmwar':openModal('confirmwar',el.dataset.owner);break;
case'build':if(run(()=>game.build(selected,el.dataset.id))){closeModal();toast(L("工人开始建造，结束回合后推进进度。"));}break;
case'promotion':if(run(()=>game.promote(selected,el.dataset.id))){closeModal();toast(L("单位晋升完成。"));}break;
case'choosefaith':if(run(()=>game.chooseFaith(el.dataset.id)))toast(L("信仰增益已在所有城市生效。"));break;
case'greatperson':if(run(()=>game.greatPerson(el.dataset.id))){closeModal();toast(L("伟人的贡献已加入帝国。"));}break;
case'vote':if(run(()=>game.vote()))openModal('victory');break;
case'export':exportSave();break;case'import':$('#import-file').click();break;
case'load':openModal('loadconfirm');break;case'loadnow':{const saved=JSON.parse(localStorage.getItem('hellas-save'));validateSave(saved);localStorage.setItem('hellas-autosave',JSON.stringify(saved));location.reload();break;}
case'restart':{const fresh=new Game();fresh.s=fresh.create(Math.floor(Math.random()*1000000));fresh.reveal();localStorage.setItem('hellas-autosave',fresh.serialize());location.reload();break;}
case'sound':sound=!sound;ambient.toggle(sound);renderModal();toast(sound?L("环境音乐已开启。"):L("环境音乐已关闭。"));break;
case'home':world.home();break;case'zoomIn':world.zoom(.83);break;case'zoomOut':world.zoom(1.2);break;case'rotate':world.rotate(Math.PI/6);break;case'grid':el?.classList.toggle('active',world.toggleGrid());break;case'endturn':nextTurn();break;case'deselect':selectUnit(null);break;case'fortify':run(()=>game.fortify(selected));break;case'wake':run(()=>game.wake(selected));break;case'skip':run(()=>game.skip(selected));break;case'found':run(()=>game.found(selected));break;case'upgrade':run(()=>game.upgrade(selected));break;case'nextunit':{const list=game.s.units.filter(u=>u.owner==='greece'&&u.moves>0&&!u.sleep&&!u.job);if(!list.length){toast(L("所有部队已完成行动。"));break;}const i=list.findIndex(u=>u.id===selected);selectUnit(list[(i+1)%list.length].id,true);break;}case'close':closeModal();break;case'save':save(false);if(modalView==='menu')renderModal();break;default:openModal(a);}}
document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(el)handleAction(el.dataset.action,el);});$('#modal').addEventListener('cancel',()=>{modalView=null;modalArg=null;});$('#modal').addEventListener('click',e=>{if(e.target===$('#modal'))closeModal();});
window.addEventListener('keydown',e=>{if(busy||e.repeat&&!['q','e'].includes(e.key.toLowerCase())){e.preventDefault();return;}if(e.target.matches('input,select,textarea'))return;if($('#modal').open){if(e.key==='Escape')closeModal();return;}if(e.key==='Enter'){e.preventDefault();nextTurn();}if(e.key==='Tab'){e.preventDefault();handleAction('nextunit');}if(e.key.toLowerCase()==='t')openModal('tech');if(e.key.toLowerCase()==='p')openModal('policy');if(e.key.toLowerCase()==='h')openModal('help');if(e.key.toLowerCase()==='g')world.toggleGrid();if(e.key.toLowerCase()==='f')run(()=>game.fortify(selected));if(e.key.toLowerCase()==='q')world.rotate(.2);if(e.key.toLowerCase()==='e')world.rotate(-.2);if(e.key==='Home')world.home();if(e.key==='Escape')openModal('menu');});
render();controls();world=new World($('#world'),game,tileClick,tileHover);world.select(selected);game.onChange(render);window.hellas={get game(){return game;},get world(){return world;},openModal,selectUnit};

const modelContext=document.modelContext;
if(modelContext?.registerTool){
const lifecycle=new AbortController();
const tools=[{name:'read_hellas_empire',title:L("查看希腊帝国"),description:'Read the current turn, empire resources, active research, owned cities and units. Does not advance the game.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({turn:game.s.turn,gold:game.s.gold,culture:game.s.culture,research:game.s.research,yields:game.yields(),cities:game.owned().map(c=>({id:c.id,name:L(c.name),pop:c.pop,production:c.project})),units:game.s.units.filter(u=>u.owner==='greece').map(u=>({id:u.id,type:u.type,tile:u.tile,moves:u.moves,hp:u.hp}))})},{name:'set_hellas_research',title:L("选择科技研究"),description:'Set the active research to an unlocked technology. This changes the visible research panel without advancing the turn.',inputSchema:{type:'object',properties:{technology:{type:'string',enum:TECHS.map(t=>t.id)}},required:['technology'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!input||typeof input.technology!=='string'||!TECH[input.technology])throw Error('Unknown technology');if(!game.techAvailable(input.technology))throw Error('Technology prerequisites are not met or it is already complete');game.research(input.technology);return{research:game.s.research,name:L(TECH[game.s.research].name)};}}];
for(const t of tools)Promise.resolve(modelContext.registerTool(t,{signal:lifecycle.signal})).catch(e=>console.warn('WebMCP registration:',e.message));window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
}
