export const VERSION=1;
export const TERRAIN={grass:{name:'草原',color:0x73935a,food:2,production:0},plains:{name:'平原',color:0xa5a569,food:1,production:1},forest:{name:'森林',color:0x54754c,food:1,production:1,cost:2,defense:.25},hill:{name:'丘陵',color:0x96906b,food:0,production:2,cost:2,defense:.25},desert:{name:'沙漠',color:0xc6ad77,food:0,production:0},mountain:{name:'山脉',color:0x959387,blocked:true},water:{name:'海岸',color:0x238c99,food:1,gold:1,water:true},ocean:{name:'深海',color:0x20627b,food:1,water:true},tundra:{name:'冻土',color:0xa4ad95,food:1,production:0}};
export const RESOURCES={wheat:{name:'小麦',icon:'wheat',food:1},horses:{name:'马匹',icon:'horse',production:1,strategic:true,tech:'husbandry',improvement:'pasture'},iron:{name:'铁矿',icon:'anvil',production:1,strategic:true,tech:'iron',improvement:'mine'},marble:{name:'大理石',icon:'columns',production:1,luxury:true,improvement:'quarry'},wine:{name:'葡萄酒',icon:'grape',gold:2,luxury:true,improvement:'plantation'},gold:{name:'金矿',icon:'coin',gold:2,luxury:true,improvement:'mine'},fish:{name:'鱼群',icon:'fish',food:2},silk:{name:'丝绸',icon:'leaf',gold:2,luxury:true,improvement:'plantation'}};
const tech=(id,name,era,cost,prereqs,icon,description)=>({id,name,era,cost,prereqs,icon,description});
export const ERAS=['远古时代','古典时代','中古时代','文艺复兴','工业时代','现代'];
export const TECHS=[
tech('agriculture','农业',0,0,[],'wheat','解锁农场，开启定居生活。'),
tech('pottery','制陶术',0,25,['agriculture'],'vase','解锁粮仓与神社。'),tech('mining','采矿',0,25,['agriculture'],'pickaxe','解锁矿山。'),tech('husbandry','畜牧业',0,30,['agriculture'],'horse','显示马匹，解锁牧场。'),tech('archery','弓箭',0,30,['agriculture'],'bow','解锁弓箭手。'),
tech('writing','文字',0,50,['pottery'],'scroll','解锁图书馆与大图书馆。'),tech('calendar','历法',0,45,['pottery'],'sun','解锁种植园与巨石阵。'),tech('masonry','砌砖术',0,45,['mining'],'wall','解锁城墙、采石场与金字塔。'),tech('bronze','青铜器',0,50,['mining'],'shield','解锁希腊重装步兵与军营。'),tech('wheel','轮子',0,45,['husbandry'],'wheel','解锁道路与水磨坊。'),tech('sailing','航海',0,45,['pottery'],'ship','解锁三列桨战船与海上移动。'),
tech('philosophy','哲学',1,85,['writing'],'columns','解锁神庙与国家学院。'),tech('horseback','骑术',1,80,['wheel','husbandry'],'horse','解锁希腊伙伴骑兵。'),tech('iron','铁器',1,90,['bronze'],'sword','显示铁矿，解锁剑士。'),tech('mathematics','数学',1,80,['archery','wheel'],'compass','解锁投石车与空中花园。'),tech('construction','建筑学',1,85,['masonry'],'hammer','解锁复合弓兵与竞技场。'),tech('currency','货币',1,90,['mathematics'],'coin','解锁市场。'),
tech('civil','文官制度',2,145,['philosophy','horseback'],'scroll','解锁长枪兵；农场额外产出粮食。'),tech('theology','神学',2,140,['philosophy','calendar'],'star','解锁圣索菲亚大教堂。'),tech('engineering','工程学',2,130,['mathematics','construction'],'gear','解锁引水渠。'),tech('metal','金属铸造',2,145,['iron'],'anvil','解锁工坊。'),tech('education','教育',2,180,['civil','theology'],'flask','解锁大学。'),tech('chivalry','骑士制度',2,175,['civil','currency'],'horse','解锁骑士与城堡。'),tech('machinery','机械',2,175,['engineering','metal'],'bow','解锁弩手。'),
tech('printing','印刷术',3,240,['education','machinery'],'book','解锁外交大会与文化印刷。'),tech('gunpowder','火药',3,250,['metal','education'],'burst','解锁火枪手。'),tech('astronomy','天文学',3,220,['education','sailing'],'compass','解锁远洋航行与天文台。'),tech('banking','银行业',3,235,['chivalry','education'],'coin','解锁银行。'),tech('acoustics','声学',3,240,['education'],'music','解锁歌剧院。'),tech('chemistry','化学',3,280,['gunpowder'],'flask','解锁加农炮；矿山产能增加。'),
tech('industrial','工业化',4,350,['banking','chemistry'],'factory','解锁工厂。'),tech('scientific','科学理论',4,340,['astronomy','acoustics'],'flask','解锁公立学校。'),tech('rifling','膛线',4,360,['gunpowder','printing'],'sword','解锁步枪兵。'),tech('steam','蒸汽动力',4,380,['industrial','scientific'],'gear','解锁铁甲舰。'),tech('electricity','电力',4,420,['scientific','industrial'],'bolt','解锁研究实验室。'),
tech('radio','无线电',5,480,['electricity'],'signal','解锁广播塔。'),tech('combustion','内燃机',5,490,['steam','rifling'],'tank','解锁坦克。'),tech('flight','飞行',5,500,['steam'],'wing','解锁战斗机。'),tech('rocketry','火箭学',5,600,['flight','radio'],'rocket','解锁航天计划；完成后获得科技胜利。')];
export const TECH=Object.fromEntries(TECHS.map(x=>[x.id,x]));
const unit=(name,icon,cost,strength,moves,tech,extra={})=>({name,icon,cost,strength,moves,tech,...extra});
export const UNITS={
warrior:unit('勇士','sword',25,8,2,null,{upgrade:'swordsman'}),scout:unit('斥候','compass',20,5,3,null,{vision:3,roughFree:true}),settler:unit('移民','flag',65,0,2,null,{civilian:true}),worker:unit('工人','hammer',35,0,2,null,{civilian:true}),archer:unit('弓箭手','bow',30,5,2,'archery',{ranged:7,range:2,upgrade:'composite'}),hoplite:unit('重装步兵','shield',40,13,2,'bronze',{unique:true,antiHorse:true,upgrade:'pikeman'}),cavalry:unit('伙伴骑兵','horse',65,14,5,'horseback',{unique:true,resource:'horses',mounted:true,upgrade:'knight'}),swordsman:unit('剑士','sword',65,14,2,'iron',{resource:'iron',upgrade:'musket'}),catapult:unit('投石车','target',60,7,2,'mathematics',{ranged:8,range:2,siege:true,upgrade:'cannon'}),composite:unit('复合弓兵','bow',55,7,2,'construction',{ranged:11,range:2,upgrade:'crossbow'}),trireme:unit('三列桨战船','ship',55,10,4,'sailing',{naval:true,upgrade:'ironclad'}),pikeman:unit('长枪兵','shield',80,16,2,'civil',{antiHorse:true,upgrade:'musket'}),knight:unit('骑士','horse',100,20,4,'chivalry',{mounted:true,resource:'horses',upgrade:'tank'}),crossbow:unit('弩手','bow',100,13,2,'machinery',{ranged:18,range:2,upgrade:'rifle'}),musket:unit('火枪手','sword',120,24,2,'gunpowder',{upgrade:'rifle'}),cannon:unit('加农炮','target',140,14,2,'chemistry',{ranged:26,range:2,siege:true}),rifle:unit('步枪兵','sword',170,34,2,'rifling'),ironclad:unit('铁甲舰','ship',180,45,4,'steam',{naval:true}),tank:unit('坦克','tank',220,60,5,'combustion',{mounted:true}),fighter:unit('战斗机','wing',240,50,6,'flight',{ranged:55,range:4,flying:true})};
const b=(name,icon,cost,tech,description,yields={},extra={})=>({name,icon,cost,tech,description,yields,...extra});
export const BUILDINGS={monument:b('纪念碑','columns',30,null,'每回合 +2 文化。',{culture:2}),granary:b('粮仓','wheat',40,'pottery','每回合 +2 粮食。',{food:2}),shrine:b('神社','star',35,'pottery','每回合 +2 信仰。',{faith:2}),library:b('图书馆','book',55,'writing','每回合 +3 科研。',{science:3}),walls:b('城墙','wall',50,'masonry','城市防御 +8，生命上限 +50。',{}, {defense:8,hp:50}),barracks:b('军营','shield',50,'bronze','新训练的军队获得 15 经验。',{}, {xp:15}),watermill:b('水磨坊','wheel',65,'wheel','每回合 +2 粮食、+1 产能。',{food:2,production:1}),temple:b('神庙','columns',75,'philosophy','每回合 +3 信仰。',{faith:3}),college:b('国家学院','flask',110,'philosophy','每回合 +6 科研。',{science:6}),colosseum:b('竞技场','laurel',80,'construction','幸福度 +3。',{happiness:3}),market:b('市场','coin',80,'currency','每回合 +5 金币。',{gold:5}),aqueduct:b('引水渠','wave',95,'engineering','城市增长后保留 40% 粮食。',{food:1}),workshop:b('工坊','anvil',100,'metal','每回合 +4 产能。',{production:4}),university:b('大学','flask',135,'education','每回合 +8 科研。',{science:8}),castle:b('城堡','wall',100,'chivalry','城市防御 +10。',{}, {defense:10}),bank:b('银行','coin',150,'banking','每回合 +8 金币。',{gold:8}),observatory:b('天文台','compass',145,'astronomy','每回合 +7 科研。',{science:7}),opera:b('歌剧院','music',145,'acoustics','每回合 +6 文化。',{culture:6}),factory:b('工厂','factory',180,'industrial','每回合 +8 产能。',{production:8}),school:b('公立学校','book',180,'scientific','每回合 +12 科研。',{science:12}),lab:b('研究实验室','flask',230,'electricity','每回合 +18 科研。',{science:18}),broadcast:b('广播塔','signal',230,'radio','每回合 +12 文化。',{culture:12})};
export const WONDERS={greatlibrary:b('大图书馆','book',140,'writing','+6 科研，+2 文化，全帝国唯一。',{science:6,culture:2},{wonder:true}),pyramids:b('金字塔','mountain',130,'masonry','工人建造速度加倍，+2 文化。',{culture:2},{wonder:true}),stonehenge:b('巨石阵','sun',120,'calendar','+6 信仰，+2 文化。',{faith:6,culture:2},{wonder:true}),gardens:b('空中花园','leaf',150,'mathematics','+6 粮食，+2 幸福。',{food:6,happiness:2},{wonder:true}),hagia:b('圣索菲亚大教堂','star',220,'theology','+8 信仰，+3 文化。',{faith:8,culture:3},{wonder:true}),apollo:b('阿波罗计划','rocket',650,'rocketry','完成人类的航天事业，获得科技胜利。',{}, {wonder:true})};
export const POLICIES=[
{id:'tradition',name:'传统',icon:'columns',era:0,desc:'让一座伟大的城市成为文明的中心。',nodes:[['tradition_open','传统开门',null,'首都 +3 文化。'],['aristocracy','贵族政治','tradition_open','奇观建造产能 +25%。'],['oligarchy','寡头政治','tradition_open','城市防御 +30%。'],['monarchy','君主制','oligarchy','首都每 2 人口 +1 金币、+1 幸福。'],['landed','地主精英','aristocracy','所有城市 +2 粮食。']]},
{id:'liberty',name:'自主',icon:'flag',era:0,desc:'将自由的城邦连成一片繁荣的国土。',nodes:[['liberty_open','自主开门',null,'每座城市 +1 文化。'],['republic','共和制','liberty_open','每座城市 +2 产能。'],['collective','集体统治','republic','首都获得一支免费移民。'],['citizenship','公民制','liberty_open','获得免费工人，改良速度 +1。'],['meritocracy','精英政治','citizenship','每座城市 +2 幸福。']]},
{id:'honor',name:'荣誉',icon:'sword',era:0,desc:'以纪律和勇气铸造无坚不摧的军队。',nodes:[['honor_open','荣誉开门',null,'对野蛮人伤害 +33%，击杀获得文化。'],['warriorcode','战士法典','honor_open','所有单位战斗力 +10%。'],['discipline','军事纪律','honor_open','邻近友军时战斗力 +15%。'],['military','军事传统','warriorcode','单位获得双倍经验。'],['army','职业军队','discipline','单位升级费用减半。']]},
{id:'patronage',name:'赞助',icon:'handshake',era:1,desc:'用持久的友谊筑起希腊的影响力。',nodes:[['patronage_open','赞助开门',null,'城邦影响力衰减再降低 25%。'],['philanthropy','慈善事业','patronage_open','赠金获得的影响力 +25%。'],['consulates','领事馆','patronage_open','和平城邦的影响力最低恢复至 20。'],['scholasticism','经院哲学','philanthropy','每个城邦盟友 +5 科研。'],['federation','城邦联盟','consulates','每个城邦盟友 +4 金币、+2 幸福。']]},
{id:'commerce',name:'商业',icon:'coin',era:2,desc:'让爱琴海的财富流入你的国库。',nodes:[['commerce_open','商业开门',null,'金币总收入 +20%。'],['tradeunions','贸易联盟','commerce_open','道路维护费用归零。'],['mercantilism','重商主义','commerce_open','金币购买生产项目便宜 25%。'],['entrepreneur','企业精神','tradeunions','每座城市 +3 产能。'],['protectionism','保护主义','mercantilism','奢侈资源额外 +2 幸福。']]},
{id:'rationalism',name:'理性',icon:'flask',era:3,desc:'求知与探索，引领文明走向未来。',nodes:[['rationalism_open','理性开门',null,'科研总产出 +15%。'],['secularism','世俗主义','rationalism_open','每座城市 +4 科研。'],['humanism','人文主义','rationalism_open','文化总产出 +20%。'],['freethought','自由思想','secularism','科研总产出再增加 20%。'],['sovereignty','主权','humanism','每个已建科研建筑 +2 金币。']]}];
export const POLICY=Object.fromEntries(POLICIES.flatMap(b=>b.nodes.map(n=>[n[0],{id:n[0],name:n[1],prereq:n[2],desc:n[3],branch:b.id,era:b.era}])));
export const IMPROVEMENTS={farm:{name:'农场',icon:'wheat',tech:'agriculture',turns:2,food:1,terrains:['grass','plains','desert']},mine:{name:'矿山',icon:'pickaxe',tech:'mining',turns:3,production:2,terrains:['hill','grass','plains']},pasture:{name:'牧场',icon:'horse',tech:'husbandry',turns:2,production:1,food:1,terrains:['grass','plains']},quarry:{name:'采石场',icon:'anvil',tech:'masonry',turns:3,production:2,terrains:['hill','grass','plains']},plantation:{name:'种植园',icon:'leaf',tech:'calendar',turns:3,gold:2,food:1,terrains:['grass','plains','forest']},road:{name:'道路',icon:'route',tech:'wheel',turns:1,terrains:['grass','plains','forest','hill','desert','tundra']}};
export const FACTIONS={greece:{name:'希腊',leader:'亚历山大',color:'#54b2e4',hex:0x58b7ec,icon:'laurel'},persia:{name:'波斯帝国',leader:'大流士一世',color:'#d16a5b',hex:0xc75447,icon:'sun'},sparta:{name:'斯巴达',leader:'列奥尼达',color:'#d1775a',hex:0xcb7256,icon:'shield',type:'军事',bonus:'盟友每 10 回合赠送一支军队'},knossos:{name:'克诺索斯',leader:'城邦议会',color:'#70c3ae',hex:0x73c1aa,icon:'wheat',type:'海洋',bonus:'友邦首都 +3 粮食，盟友所有城市 +3 粮食'},ephesus:{name:'以弗所',leader:'城邦议会',color:'#bf96d3',hex:0xbb8bd0,icon:'music',type:'文化',bonus:'友邦 +3 文化，盟友 +6 文化'},sidon:{name:'西顿',leader:'城邦议会',color:'#e2b966',hex:0xe0b463,icon:'coin',type:'商业',bonus:'友邦 +3 金币，盟友 +6 金币'},barbarian:{name:'野蛮人',color:'#b83f40',hex:0xae3436,icon:'sword'}};
