import {TERRAIN,RESOURCES,TECHS,TECH,UNITS,BUILDINGS,WONDERS,POLICIES,POLICY,IMPROVEMENTS,VERSION} from './data.js';
export const W=28,H=20;
const dirs=[[1,0],[1,-1],[0,-1],[-1,0],[-1,1],[0,1]];
export const coord=(c,r)=>({q:c-Math.floor(r/2),r});
export const distance=(a,b)=>(Math.abs(a.q-b.q)+Math.abs(a.r-b.r)+Math.abs(a.q+a.r-b.q-b.r))/2;
export const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
export function seeded(seed){return()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296;};}
export class Game{
constructor(saved){this.listeners=[];this.s=saved||this.create();this.reveal();}
onChange(fn){this.listeners.push(fn);}
emit(){this.reveal();this.listeners.forEach(fn=>fn(this.s));}
log(text,type='info'){this.s.log.unshift({text,type,turn:this.s.turn,id:++this.s.serial});this.s.log=this.s.log.slice(0,100);}
create(seed=73467){const rand=seeded(seed);const s={version:VERSION,seed,turn:1,serial:100,gold:110,culture:0,faith:0,totalCulture:0,science:0,research:'pottery',techs:['agriculture'],policies:[],tiles:[],units:[],cities:[],wars:['sparta','barbarian'],influence:{sparta:-60,knossos:15,ephesus:10,sidon:5},quests:{sparta:'camp',knossos:'trade',ephesus:'wonder',sidon:'camp'},questDone:[],routes:[],log:[],pantheon:null,religion:null,greatPoints:0,greatPeople:0,golden:0,goldenProgress:0,victory:null,cityCounter:1,aiCounter:0};
for(let r=0;r<H;r++)for(let c=0;c<W;c++){const a=coord(c,r),n=rand();let west=c<14+Math.sin(r*.53)*1.5&&r<16,east=c>20+Math.sin(r*.48)*1.2;let island=(c-13)**2+(r-17)**2<7||(c-17)**2+(r-12)**2<2;let land=west||east||island;let terrain=!land?(c>14&&c<20?'ocean':'water'):n<.16?'forest':n<.29?'hill':n<.33?'mountain':n<.62?'plains':'grass';if(land&&r<3)terrain=n<.22?'mountain':'tundra';if(east&&r>10&&n<.35)terrain='desert';let resource=null;if(land&&terrain!=='mountain'&&rand()<.22)resource=['wheat','horses','iron','marble','wine','gold','silk'][Math.floor(rand()*7)];if(!land&&rand()<.1)resource='fish';s.tiles.push({id:r*W+c,c,r,q:a.q,terrain,resource,owner:null,improvement:null,road:false,explored:false,visible:false,ruin:land&&terrain!=='mountain'&&rand()<.025,camp:false,height:terrain==='hill'?.42:terrain==='mountain'?.55:land?.18:0});}
this.s=s;
const city=(name,owner,c,r,pop=2)=>{let t=this.tile(c,r);t.terrain='plains';t.height=.22;t.resource=null;t.ruin=false;for(const n of this.neighbors(t)){if(n.terrain==='mountain'){n.terrain='hill';n.height=.3;}}const city={id:++s.serial,name,owner,tile:t.id,pop,food:0,production:0,project:owner==='greece'?'monument':'warrior',projectType:owner==='greece'?'building':'unit',buildings:[],hp:200,maxHp:200,expanded:0,border:0,focus:'balanced',fired:false,capital:owner==='greece'||owner==='persia'};s.cities.push(city);this.claim(city,1);return city;};
city('雅典','greece',10,9,2);city('斯巴达','sparta',6,13,3);city('克诺索斯','knossos',13,17,3);city('以弗所','ephesus',22,10,3);city('西顿','sidon',24,16,3);city('波斯波利斯','persia',24,5,4);
for(const [c,r,res] of [[10,8,'wheat'],[11,9,'horses'],[9,10,'marble'],[8,8,'iron'],[12,10,'wine']]){let t=this.tile(c,r);t.resource=res;t.terrain=res==='iron'?'hill':'grass';t.height=res==='iron'?.4:.18;}
this.addUnit('warrior','greece',this.tile(11,9).id);this.addUnit('scout','greece',this.tile(10,7).id);this.addUnit('worker','greece',this.tile(9,9).id);this.addUnit('hoplite','sparta',this.tile(7,12).id);this.addUnit('archer','sparta',this.tile(6,13).id);this.addUnit('warrior','persia',this.tile(23,5).id);this.addUnit('archer','persia',this.tile(24,6).id);
for(const [c,r] of [[4,5],[15,4],[22,17]]){let t=this.tile(c,r);t.terrain='plains';t.height=.18;t.camp=true;t.ruin=false;this.addUnit('warrior','barbarian',t.id);}
for(const [c,r] of [[8,6],[12,12],[17,8]]){const t=this.tile(c,r);if(!TERRAIN[t.terrain].water){t.ruin=true;t.camp=false;}}
this.claim(s.cities[0],2);this.log('亚历山大，雅典已奠基。探索爱琴海，书写希腊的命运。','gold');return s;}
tile(c,r){return this.s.tiles[r*W+c];}
at(id){return this.s.tiles[id];}
neighbors(t){return dirs.map(([q,r])=>{let nr=t.r+r,nq=t.q+q,c=nq+Math.floor(nr/2);return nr>=0&&nr<H&&c>=0&&c<W?this.tile(c,nr):null;}).filter(Boolean);}
unit(id){return this.s.units.find(u=>u.id===id);}
city(id){return this.s.cities.find(c=>c.id===id);}
cityAt(id){return this.s.cities.find(c=>c.tile===id);}
unitsAt(id){return this.s.units.filter(u=>u.tile===id);}
owned(){return this.s.cities.filter(c=>c.owner==='greece');}
has(id){return this.s.techs.includes(id);}
policy(id){return this.s.policies.includes(id);}
isWar(owner){return this.s.wars.includes(owner);}
addUnit(type,owner,tile){const u={id:++this.s.serial,type,owner,tile,hp:100,moves:UNITS[type].moves,xp:0,promotions:[],fortified:false,sleep:false,job:null,attacked:false};this.s.units.push(u);return u;}
claim(city,radius){const t=this.at(city.tile);for(const v of this.s.tiles){if(distance(t,v)<=radius&&(!v.owner||v.owner===city.owner))v.owner=city.owner;}}
reveal(){const s=this.s;for(const t of s.tiles)t.visible=false;const sources=[...s.units.filter(u=>u.owner==='greece').map(u=>[this.at(u.tile),UNITS[u.type].vision||2]),...this.owned().map(c=>[this.at(c.tile),3]),...s.cities.filter(c=>s.influence[c.owner]>=60&&!this.isWar(c.owner)).map(c=>[this.at(c.tile),2])];for(const [p,r]of sources)for(const t of s.tiles)if(distance(p,t)<=r){t.visible=true;t.explored=true;}}
era(){return Math.max(...this.s.techs.map(id=>TECH[id].era));}
resourceCount(resource){return this.s.tiles.filter(t=>t.owner==='greece'&&t.resource===resource&&(this.cityAt(t.id)||t.improvement===RESOURCES[resource].improvement)&&(!RESOURCES[resource].tech||this.has(RESOURCES[resource].tech))).length*2;}
resourceAvailable(resource){return this.resourceCount(resource)-this.s.units.filter(u=>u.owner==='greece'&&UNITS[u.type].resource===resource).length;}
tileYield(t){const def=TERRAIN[t.terrain],i=IMPROVEMENTS[t.improvement],r=RESOURCES[t.resource];const y={food:def.food||0,production:def.production||0,gold:def.gold||0};if(r&&(!r.tech||this.has(r.tech))){for(const k of Object.keys(y))y[k]+=r[k]||0;}if(i){for(const k of Object.keys(y))y[k]+=i[k]||0;if(i===IMPROVEMENTS.farm&&this.has('civil'))y.food++;if(i===IMPROVEMENTS.mine&&this.has('chemistry'))y.production++;}return y;}
workedTiles(city){const center=this.at(city.tile);const candidates=this.s.tiles.filter(t=>t.id!==center.id&&t.owner===city.owner&&distance(t,center)<=3&&!TERRAIN[t.terrain].blocked);const score=t=>{const y=this.tileYield(t);return city.focus==='food'?y.food*5+y.production:city.focus==='production'?y.production*5+y.food:city.focus==='gold'?y.gold*5+y.food:y.food*2.4+y.production*2+y.gold;};return candidates.sort((a,b)=>score(b)-score(a)).slice(0,city.pop);}
cityYield(city){const player=city.owner==='greece';const y={food:2,production:3,gold:3,science:city.pop+1,culture:1,faith:0,happiness:0};for(const t of this.workedTiles(city)){const d=this.tileYield(t);for(const k in d)y[k]+=d[k];}for(const b of city.buildings){for(const[k,v]of Object.entries((BUILDINGS[b]||WONDERS[b]).yields))y[k]+=v;}
if(player){if(this.policy('tradition_open')&&city.capital)y.culture+=3;if(this.policy('liberty_open'))y.culture++;if(this.policy('republic'))y.production+=2;if(this.policy('landed'))y.food+=2;if(this.policy('meritocracy'))y.happiness+=2;if(this.policy('monarchy')&&city.capital){y.gold+=Math.floor(city.pop/2);y.happiness+=Math.floor(city.pop/2);}if(this.policy('entrepreneur'))y.production+=3;if(this.policy('secularism'))y.science+=4;if(this.policy('sovereignty'))y.gold+=city.buildings.filter(b=>(BUILDINGS[b]||WONDERS[b]).yields.science).length*2;if(this.s.influence.knossos>=60&&!this.isWar('knossos')||city.capital&&this.s.influence.knossos>=30&&!this.isWar('knossos'))y.food+=3;if(this.s.pantheon==='fertility')y.food+=1;if(this.s.pantheon==='craft')y.production+=1;if(this.s.pantheon==='wisdom')y.science+=1;if(this.s.religion==='tithe')y.gold+=Math.ceil(city.pop/2);if(this.s.religion==='arts')y.culture+=3;if(this.s.religion==='learning')y.science+=3;if(this.s.golden>0){y.gold=Math.ceil(y.gold*1.2);y.production=Math.ceil(y.production*1.2);y.culture=Math.ceil(y.culture*1.2);}}
y.surplus=y.food-city.pop*2;return y;}
yields(){let y={food:0,production:0,gold:0,science:0,culture:0,faith:0,happiness:12,maintenance:0};for(const c of this.owned()){const cy=this.cityYield(c);for(const k in y)y[k]+=cy[k]||0;y.happiness-=c.pop+2;}
const lux=new Set(this.s.tiles.filter(t=>t.owner==='greece'&&RESOURCES[t.resource]?.luxury&&t.improvement===RESOURCES[t.resource].improvement).map(t=>t.resource));y.happiness+=lux.size*(this.policy('protectionism')?6:4);
for(const [owner,value]of Object.entries(this.s.influence)){if(this.isWar(owner))continue;if(owner==='ephesus')y.culture+=value>=60?6:value>=30?3:0;if(owner==='sidon')y.gold+=value>=60?6:value>=30?3:0;if(value>=60){if(this.policy('scholasticism'))y.science+=5;if(this.policy('federation')){y.gold+=4;y.happiness+=2;}}}
for(const r of this.s.routes)if(!this.isWar(r.owner)){y.gold+=r.gold;y.science+=r.science;}
y.maintenance=Math.max(0,this.s.units.filter(u=>u.owner==='greece'&&!UNITS[u.type].civilian).length-3)+this.owned().reduce((a,c)=>a+Math.floor(c.buildings.length/3),0)+(this.policy('tradeunions')?0:Math.floor(this.s.tiles.filter(t=>t.road&&t.owner==='greece').length/3));y.gold=Math.round(y.gold*(this.policy('commerce_open')?1.2:1))-y.maintenance;y.science=Math.round(y.science*(1+(this.policy('rationalism_open')?.15:0)+(this.policy('freethought')?.2:0)));y.culture=Math.round(y.culture*(this.policy('humanism')?1.2:1));return y;}
techAvailable(id){return !this.has(id)&&TECH[id].prereqs.every(p=>this.has(p));}
research(id){if(!this.techAvailable(id))return this.fail('请先研究前置科技。');this.s.research=id;this.emit();return true;}
policyCost(){return Math.round(25+this.s.policies.length**1.55*13);}
adopt(id){const p=POLICY[id];if(this.policy(id)||p.prereq&&!this.policy(p.prereq)||p.era>this.era())return this.fail('尚未满足政策的前置条件。');const cost=this.policyCost();if(this.s.culture<cost)return this.fail('文化值不足。');this.s.culture-=cost;this.s.policies.push(id);if(['collective','citizenship'].includes(id)){const c=this.owned()[0];if(c)this.spawnNear(id==='collective'?'settler':'worker','greece',c.tile);}this.log(`采纳政策：${p.name}。`,'culture');this.emit();return true;}
fail(msg){this.error=msg;return false;}
canEnter(u,t){const d=UNITS[u.type];if(t.terrain==='mountain'&&!d.flying)return false;if(d.naval&&!TERRAIN[t.terrain].water&&!this.cityAt(t.id))return false;if(!d.naval&&TERRAIN[t.terrain].water&&!d.flying&&(!this.has('sailing')||t.terrain==='ocean'&&!this.has('astronomy')))return false;if(t.owner&&t.owner!==u.owner){if(u.owner==='greece'&&!this.isWar(t.owner)&&(this.s.influence[t.owner]||0)<30)return false;}const same=this.unitsAt(t.id).find(v=>v.id!==u.id&&v.owner===u.owner&&!!UNITS[v.type].civilian===!!d.civilian);return !same;}
moveCost(u,to,from=this.at(u.tile)) {
 if(UNITS[u.type].flying||UNITS[u.type].roughFree)return 1;
 if(to.road&&from.road)return .5;
 return TERRAIN[to.terrain].cost||1;
}
crossesEnemyZone(u,from,to) {
 if(UNITS[u.type].flying)return false;
 const water=!!TERRAIN[from.terrain].water;
 if(!!TERRAIN[to.terrain].water!==water)return false;
 return this.s.units.some(enemy=>{
  const enemyType=UNITS[enemy.type],tile=this.at(enemy.tile);
  const hostile=u.owner==='greece'?this.isWar(enemy.owner):enemy.owner==='greece'&&this.isWar(u.owner);
  return hostile&&!enemyType.civilian&&!enemyType.flying&&!!enemyType.naval===water
   &&!!TERRAIN[tile.terrain].water===water&&distance(from,tile)===1&&distance(to,tile)===1;
 });
}
stepCost(u,from,to,remaining) {
 // Civ V: any remaining MP permits one legal step. Crossing the same
 // enemy unit's zone of control spends all remaining MP, without combat.
 return this.crossesEnemyZone(u,from,to)?remaining:Math.min(remaining,this.moveCost(u,to,from));
}
reachable(u) {
 const start=this.at(u.tile),best=new Map([[start.id,0]]),queue=[start];
 while(queue.length){
  const from=queue.shift(),spent=best.get(from.id),remaining=u.moves-spent;
  if(remaining<=0)continue;
  for(const to of this.neighbors(from)){
   if(u.owner==='greece'&&!to.explored)continue;
   if(!this.canEnter(u,to)||this.unitsAt(to.id).some(other=>other.owner!==u.owner))continue;
   const city=this.cityAt(to.id);if(city&&city.owner!==u.owner)continue;
   const cost=spent+this.stepCost(u,from,to,remaining);
   if(!best.has(to.id)||cost<best.get(to.id)){best.set(to.id,cost);queue.push(to);}
  }
 }
 return best;
}
move(id,tileId){if(this.s.victory)return false;const u=this.unit(id),dest=this.at(tileId);if(!u||u.owner!=='greece')return false;const foe=this.unitsAt(tileId).find(e=>e.owner!=='greece'&&dest.visible);const city=this.cityAt(tileId);if(foe||city&&city.owner!=='greece'){const owner=foe?.owner||city.owner;if(!this.isWar(owner))return this.fail('这片土地属于和平势力。可在外交界面宣战。');return this.attack(u,foe||city,!!(!foe&&city));}
const costs=this.reachable(u);if(!costs.has(tileId)||tileId===u.tile)return this.fail('无法在本回合抵达此处。选择蓝色高亮地块。');u.moves-=costs.get(tileId);u.tile=tileId;u.fortified=false;u.sleep=false;u.job=null;this.onArrive(u);this.emit();return true;}
onArrive(u){if(u.owner!=='greece')return;const t=this.at(u.tile);if(t.ruin){t.ruin=false;const prize=t.id%4;if(prize===0){this.s.gold+=65;this.log('发现古代遗迹：获得 65 金币。','gold');}else if(prize===1){this.s.culture+=25;this.log('古代遗迹留下了祖先的传说：+25 文化。','culture');}else if(prize===2){this.s.science+=25;this.log('发现远古知识：+25 科研。','science');}else{u.xp+=20;this.log('探索古代遗迹：单位获得 20 经验。','info');}}if(t.camp){t.camp=false;this.s.gold+=45;this.log('清除野蛮人营地：获得 45 金币。','gold');for(const [f,q]of Object.entries(this.s.quests))if(q==='camp'&&!this.s.questDone.includes(f)){this.s.influence[f]+=45;this.s.questDone.push(f);this.log(`完成城邦委托：${f==='sidon'?'西顿':'斯巴达'}影响力 +45。`,'gold');}}}
strength(u,defending=false,target=null){const d=UNITS[u.type];let val=(defending?d.strength:d.ranged||d.strength);let bonus=u.promotions.length*.15;if(u.owner==='greece'){if(this.policy('warriorcode'))bonus+=.1;if(this.policy('honor_open')&&target?.owner==='barbarian')bonus+=.33;if(this.policy('discipline')&&this.s.units.some(v=>v.owner===u.owner&&v.id!==u.id&&distance(this.at(u.tile),this.at(v.tile))===1))bonus+=.15;}if(d.antiHorse&&target?.type&&UNITS[target.type].mounted)bonus+=.5;if(defending){bonus+=TERRAIN[this.at(u.tile).terrain].defense||0;if(u.fortified)bonus+=.4;}return val*(1+bonus)*(0.5+u.hp/200);}
cityStrength(c){let v=12+c.pop+this.era()*3+c.buildings.reduce((n,b)=>n+((BUILDINGS[b]||WONDERS[b]).defense||0),0);if(c.owner==='greece'&&this.policy('oligarchy'))v*=1.3;return v;}
combatPreview(u,target,isCity=false){let a=this.strength(u,false,target)*(isCity&&UNITS[u.type].siege?2.5:1),d=isCity?this.cityStrength(target):Math.max(1,this.strength(target,true,u));return {dealt:clamp(Math.round(30*Math.pow(a/d,1.2)),5,85),received:UNITS[u.type].ranged||!isCity&&UNITS[target.type].civilian?0:clamp(Math.round(24*Math.pow(d/a,1.2)),5,70)};}
attack(u,target,isCity=false,ai=false){const d=UNITS[u.type];if(!d.strength)return this.fail('平民单位无法攻击。');if(u.moves<=0||u.attacked)return this.fail('这个单位本回合已完成行动。');if(distance(this.at(u.tile),this.at(target.tile))>(d.range||1))return this.fail(d.ranged?'目标不在射程内。':'近战单位需要先移动到目标旁。');if(d.ranged&&!d.flying&&this.s.tiles.some(t=>t.terrain==='mountain'&&distance(this.at(u.tile),t)===1&&distance(t,this.at(target.tile))===1))return this.fail('山脉阻挡了远程攻击视线。');const hit=this.combatPreview(u,target,isCity);target.hp-=hit.dealt;u.hp-=hit.received;u.attacked=true;u.moves=d.mounted?Math.max(0,u.moves-1):0;u.fortified=false;u.sleep=false;u.job=null;u.xp+=this.policy('military')&&u.owner==='greece'?10:5;
if(isCity&&target.hp<=0){if(d.ranged){target.hp=1;}else{const former=target.owner;target.owner=u.owner;target.hp=Math.floor(target.maxHp/2);target.pop=Math.max(1,target.pop-1);target.project=null;target.production=0;for(const t of this.s.tiles)if(t.owner===former&&distance(t,this.at(target.tile))<=3)t.owner=u.owner;u.tile=target.tile;this.log(`${target.name}被${u.owner==='greece'?'希腊军队':'敌军'}占领！`,'war');if(former==='persia'&&u.owner==='greece')this.win('征服胜利','波斯波利斯已被攻克。希腊的旗帜飘扬在敌人的首都。');}}
else if(!isCity&&target.hp<=0){this.s.units=this.s.units.filter(v=>v.id!==target.id);if(!d.ranged&&u.hp>0){u.tile=target.tile;this.onArrive(u);}if(u.owner==='greece'){this.log(`${d.name}击败${UNITS[target.type].name}。`,'war');if(this.policy('honor_open'))this.s.culture+=10;}}
if(u.hp<=0){this.s.units=this.s.units.filter(v=>v.id!==u.id);this.log(`${d.name}在战斗中阵亡。`,'war');}this.s.lastCombat={tile:target.tile,dealt:hit.dealt,received:hit.received,id:++this.s.serial};if(!ai)this.emit();return true;}
fortify(id){const u=this.unit(id);if(!u)return false;u.fortified=true;u.sleep=true;u.moves=0;u.job=null;this.emit();return true;}
skip(id){const u=this.unit(id);if(!u)return false;u.moves=0;this.emit();return true;}
wake(id){const u=this.unit(id);if(!u)return false;u.sleep=false;u.fortified=false;this.emit();return true;}
heal(id){return this.fortify(id);}
promote(id,choice){const u=this.unit(id);if(!u||u.xp<(u.promotions.length+1)*15)return this.fail('经验不足，需通过战斗或遗迹积累。');if(choice==='heal'){u.hp=100;u.xp-=15;}else{u.promotions.push(choice);u.xp-=15;}this.emit();return true;}
upgrade(id){const u=this.unit(id),next=u&&UNITS[u.type].upgrade;if(!next||!this.has(UNITS[next].tech))return this.fail('尚未解锁升级兵种。');const cost=Math.round((UNITS[next].cost-UNITS[u.type].cost+20)*(this.policy('army')?1:2));if(this.at(u.tile).owner!=='greece')return this.fail('单位必须位于本国领土内。');if(this.s.gold<cost)return this.fail('金币不足。');if(UNITS[next].resource&&this.resourceAvailable(UNITS[next].resource)<=0&&UNITS[u.type].resource!==UNITS[next].resource)return this.fail('缺少战略资源。');this.s.gold-=cost;u.type=next;u.moves=0;this.emit();return true;}
found(id){const u=this.unit(id);if(!u||u.type!=='settler'||u.moves<=0)return this.fail('需要一支能够行动的移民。');const t=this.at(u.tile);if(TERRAIN[t.terrain].water||t.owner&&t.owner!=='greece'||this.s.cities.some(c=>distance(this.at(c.tile),t)<4))return this.fail('城市之间至少相隔 4 格，且需位于陆地。');const names=['科林斯','塞萨洛尼基','阿尔戈斯','米利都','罗德岛','德尔斐','迈锡尼'];const name=names[(this.s.cityCounter++-1)%names.length];const city={id:++this.s.serial,name,owner:'greece',tile:t.id,pop:1,food:0,production:0,project:'monument',projectType:'building',buildings:[],hp:200,maxHp:200,expanded:0,border:0,focus:'balanced',fired:false,capital:false};this.s.cities.push(city);this.s.units=this.s.units.filter(v=>v.id!==id);this.claim(city,1);this.log(`${name}建成。新的城邦加入希腊！`,'gold');this.emit();return true;}
build(id,kind){const u=this.unit(id),d=IMPROVEMENTS[kind];if(!u||u.type!=='worker'||u.moves<=0||!d)return this.fail('需要一支能够行动的工人。');const t=this.at(u.tile);if(t.owner!=='greece')return this.fail('只能改良自己的领土。');if(!this.has(d.tech)||!d.terrains.includes(t.terrain)||this.cityAt(t.id))return this.fail('此地无法建造这项改良。');if(kind==='road'?t.road:t.improvement===kind)return this.fail('此处已有相同设施。');if(['pasture','quarry','plantation'].includes(kind)&&RESOURCES[t.resource]?.improvement!==kind)return this.fail('此改良需要对应的资源。');u.job={kind,left:d.turns};u.moves=0;u.sleep=false;this.emit();return true;}
projectDef(type,id){return(type==='unit'?UNITS:type==='wonder'?WONDERS:BUILDINGS)[id];}
canProduce(city,type,id){const d=this.projectDef(type,id);if(!d||d.tech&&!this.has(d.tech))return false;if(type!=='unit'&&city.buildings.includes(id))return false;if(type==='wonder'&&this.s.cities.some(c=>c.buildings.includes(id)||c.id!==city.id&&c.project===id))return false;if(type==='unit'&&d.resource&&this.resourceAvailable(d.resource)<=0)return false;if(type==='unit'&&d.naval&&!this.neighbors(this.at(city.tile)).some(t=>TERRAIN[t.terrain].water))return false;if(id==='settler'&&city.pop<2)return false;return true;}
production(city,type,id,buy=false){if(city.owner!=='greece'||!this.canProduce(city,type,id))return this.fail('尚未满足建造条件，或此建筑已建成。');const d=this.projectDef(type,id);if(buy){const cost=this.purchaseCost(d);if(this.s.gold<cost)return this.fail('金币不足。');if(type==='wonder')return this.fail('奇观需要通过城市产能完成。');if(type==='unit'&&!this.spawnTile(id,city.owner,city.tile))return this.fail('城市周边没有可供新单位部署的空格。');this.s.gold-=cost;this.complete(city,type,id);}else{if(city.project!==id)city.production=0;city.project=id;city.projectType=type;}this.emit();return true;}
purchaseCost(d){return Math.round(d.cost*4*(this.policy('mercantilism')?.75:1));}
spawnTile(type,owner,tile){const d=UNITS[type];return [this.at(tile),...this.neighbors(this.at(tile)),...this.s.tiles.filter(t=>distance(t,this.at(tile))===2)].find(t=>{if(d.naval&&!TERRAIN[t.terrain].water)return false;if(!d.naval&&(TERRAIN[t.terrain].water||t.terrain==='mountain'))return false;return !this.s.units.some(u=>u.tile===t.id&&u.owner!==owner||u.tile===t.id&&!!UNITS[u.type].civilian===!!d.civilian);});}
spawnNear(type,owner,tile){const t=this.spawnTile(type,owner,tile);return t?this.addUnit(type,owner,t.id):null;}
complete(city,type,id){const d=this.projectDef(type,id);if(type==='unit'){const u=this.spawnNear(id,city.owner,city.tile);if(!u)return false;u.xp=city.buildings.includes('barracks')?15:0;}else{city.buildings.push(id);city.maxHp+=d.hp||0;city.hp=Math.min(city.hp+(d.hp||0),city.maxHp);if(id==='apollo'&&city.owner==='greece')this.win('科技胜利','阿波罗计划完成。希腊的求知精神抵达了群星。');if(type==='wonder'&&city.owner==='greece'){this.s.greatPoints+=35;for(const [f,q]of Object.entries(this.s.quests))if(q==='wonder'&&!this.s.questDone.includes(f)){this.s.influence[f]+=40;this.s.questDone.push(f);this.log('以弗所赞颂你的奇观：影响力 +40。','culture');}}}if(city.owner==='greece')this.log(`${city.name}完成${d.name}。`,type==='wonder'?'gold':'info');return true;}
focusCity(id,focus){const c=this.city(id);if(c?.owner!=='greece')return false;c.focus=focus;this.emit();return true;}
buyTile(cityId,tileId){const c=this.city(cityId),t=this.at(tileId);if(!c||c.owner!=='greece'||!t||t.owner||distance(t,this.at(c.tile))>3||!this.neighbors(t).some(n=>n.owner==='greece'))return this.fail('只能购买距城市 3 格内相邻的无主地块。');const cost=35+c.expanded*10;if(this.s.gold<cost)return this.fail('金币不足。');this.s.gold-=cost;t.owner='greece';c.expanded++;this.emit();return true;}
diplomacy(owner,action){if(owner==='barbarian'||owner==='greece')return false;if(action==='war'){if(this.isWar(owner))return false;this.s.wars.push(owner);if(owner!=='persia')this.s.influence[owner]=-60;this.s.routes=this.s.routes.filter(r=>r.owner!==owner);this.log(`你向${owner==='persia'?'波斯帝国':({sparta:'斯巴达',knossos:'克诺索斯',ephesus:'以弗所',sidon:'西顿'})[owner]}宣战。`,'war');}else if(action==='peace'){if(!this.isWar(owner))return false;const price=owner==='persia'?150:75;if(this.s.gold<price)return this.fail(`缔结和约需要 ${price} 金币。`);this.s.gold-=price;this.s.wars=this.s.wars.filter(f=>f!==owner);if(owner!=='persia')this.s.influence[owner]=-20;this.log('双方签署和约，敌对行动停止。','info');}else if(action==='gift'){if(this.isWar(owner))return this.fail('请先缔结和平。');if(this.s.gold<100)return this.fail('赠礼需要 100 金币。');this.s.gold-=100;this.s.influence[owner]+=40*(this.policy('philanthropy')?1.25:1);this.log('使者送达礼物，城邦影响力提升。','gold');}else if(action==='trade'){if(!this.has('wheel'))return this.fail('研究轮子后可建立商路。');if(this.isWar(owner))return this.fail('无法与敌对势力通商。');if(this.s.routes.some(r=>r.owner===owner))return this.fail('这条商路已经建立。');if(this.s.routes.length>=1+Math.floor(this.era()/2))return this.fail('商路容量已满；进入更高时代可增加容量。');if(this.s.gold<75)return this.fail('建立商路需要 75 金币。');this.s.gold-=75;this.s.routes.push({owner,gold:4,science:2,left:25});if(this.s.quests[owner]==='trade'&&!this.s.questDone.includes(owner)){this.s.influence[owner]+=40;this.s.questDone.push(owner);}this.log('商队出发：25 回合内每回合 +4 金币、+2 科研。','gold');}this.emit();return true;}
chooseFaith(kind){if(!this.s.pantheon){if(this.s.faith<50||!['fertility','craft','wisdom'].includes(kind))return this.fail('建立万神殿需要 50 信仰。');this.s.faith-=50;this.s.pantheon=kind;this.log('希腊万神殿建立。','gold');}else if(!this.s.religion){if(this.s.faith<200||!['tithe','arts','learning'].includes(kind))return this.fail('创立信仰需要 200 信仰。');this.s.faith-=200;this.s.religion=kind;this.log('希腊诸神的信仰传遍城邦。','gold');}else return false;this.emit();return true;}
greatPerson(kind){if(this.s.greatPeople<1)return this.fail('尚未诞生伟人。');this.s.greatPeople--;if(kind==='scientist')this.s.science+=150;else if(kind==='engineer'){const c=this.owned().find(c=>c.project);if(c)c.production+=150;else this.s.gold+=200;}else if(kind==='merchant')this.s.gold+=300;else if(kind==='artist'){this.s.culture+=150;this.s.golden+=8;}this.log('伟人的贡献将永远被希腊铭记。','gold');this.emit();return true;}
bombard(cityId,targetId){const c=this.city(cityId),u=this.unit(targetId);if(!c||!u||c.owner!=='greece'||c.fired||!this.isWar(u.owner)||!this.at(u.tile).visible||distance(this.at(c.tile),this.at(u.tile))>2)return this.fail('城市只能每回合炮击一次视野内 2 格的敌军。');u.hp-=clamp(Math.round(28*this.cityStrength(c)/Math.max(1,this.strength(u,true))),15,65);if(u.hp<=0)this.s.units=this.s.units.filter(v=>v.id!==u.id);c.fired=true;this.log(`${c.name}的守军发动远程攻击。`,'war');this.emit();return true;}
endTurn(){if(this.s.victory)return false;const s=this.s,y=this.yields();s.turn++;s.gold=Math.max(0,s.gold+y.gold);s.culture+=y.culture;s.totalCulture+=y.culture;s.faith+=y.faith;s.greatPoints+=this.owned().reduce((a,c)=>a+c.pop,0)*.5;s.goldenProgress+=Math.max(0,y.happiness);if(s.goldenProgress>=180){s.goldenProgress-=180;s.golden+=8;this.log('黄金时代开始！8 回合内金币、产能与文化 +20%。','gold');}if(s.golden>0)s.golden--;if(s.greatPoints>=100){s.greatPoints-=100;s.greatPeople++;this.log('一位伟人诞生了！在帝国总览中选择其贡献。','gold');}
if(s.research){s.science+=y.science;if(s.science>=TECH[s.research].cost){const id=s.research;s.science-=TECH[id].cost;s.techs.push(id);s.research=null;this.log(`研究完成：${TECH[id].name}。请选择下一项科技。`,'science');}}
for(const c of this.owned()){const cy=this.cityYield(c);let extra=cy.surplus;if(y.happiness<0&&extra>0)extra*=.25;if(c.project==='settler'){extra=0;}c.food+=extra;const need=15+c.pop*9;if(c.food>=need){c.food=c.buildings.includes('aqueduct')?need*.4:c.food-need;c.pop++;this.log(`${c.name}人口增长至 ${c.pop}。`,'info');}if(c.food<0){if(c.pop>1){c.pop--;c.food=0;this.log(`${c.name}发生饥荒，失去 1 人口。`,'war');}else c.food=0;}
if(c.project){let production=cy.production;if(c.projectType==='wonder'&&this.policy('aristocracy'))production*=1.25;c.production+=production;const def=this.projectDef(c.projectType,c.project);if(c.production>=def.cost){if(this.complete(c,c.projectType,c.project)){c.production=0;c.project=null;}}}c.border+=cy.culture;if(c.border>=15+c.expanded*8){const t=this.s.tiles.filter(t=>!t.owner&&distance(this.at(c.tile),t)<=3&&this.neighbors(t).some(n=>n.owner==='greece')).sort((a,b)=>(distance(this.at(c.tile),a)-distance(this.at(c.tile),b))||((b.resource?1:0)-(a.resource?1:0)))[0];if(t){t.owner='greece';c.border=0;c.expanded++;}}c.hp=Math.min(c.maxHp,c.hp+10);c.fired=false;}
for(const u of s.units.filter(u=>u.owner==='greece')){if(u.job){const speed=(this.policy('citizenship')?2:1)*(this.owned().some(c=>c.buildings.includes('pyramids'))?2:1);u.job.left-=speed;if(u.job.left<=0){const t=this.at(u.tile);if(u.job.kind==='road')t.road=true;else t.improvement=u.job.kind;this.log(`工人完成${IMPROVEMENTS[u.job.kind].name}。`,'info');u.job=null;}}
if(!u.attacked&&(u.fortified||u.moves===UNITS[u.type].moves)){u.hp=Math.min(100,u.hp+(this.at(u.tile).owner==='greece'?20:10));}}
for(const f of Object.keys(s.influence)){if(!this.isWar(f)){const base=this.policy('consulates')?20:0;s.influence[f]=s.influence[f]>base?Math.max(base,s.influence[f]-(this.policy('patronage_open')?.375:.5)):Math.min(base,s.influence[f]+2);}}
s.routes=s.routes.filter(r=>--r.left>0&&!this.isWar(r.owner));if(s.turn%10===0&&s.influence.sparta>=60&&!this.isWar('sparta')){this.spawnNear(this.has('bronze')?'hoplite':'warrior','greece',this.owned()[0].tile);this.log('盟友斯巴达赠送了一支军队。','gold');}
this.aiTurn();
// A standing fortify/sleep order does not spend the new turn's movement.
// Defending during the AI phase never counts as the player's attack.
for(const u of s.units){u.moves=u.job?0:UNITS[u.type].moves;u.attacked=false;}
if(!this.owned().length)this.win('文明覆灭','最后一座希腊城市陷落了。新的历史，等待你的下一次开局。',false);
const completeBranches=POLICIES.filter(b=>b.nodes.every(n=>this.policy(n[0]))).length;if(completeBranches>=4&&s.totalCulture>=1000)this.win('文化胜利','四条政策树已经完成，希腊思想照亮了世界。');if(s.turn>=200&&!s.victory)this.win('历史终章',`200 回合结束。希腊的最终文明评分为 ${this.score()}。`,this.score()>=s.cities.filter(c=>c.owner==='persia').reduce((a,c)=>a+c.pop*10+50,0));this.emit();return true;}
aiTurn(){const s=this.s;for(const c of s.cities.filter(c=>c.owner!=='greece')){c.hp=Math.min(c.maxHp,c.hp+8);if(s.turn%9===0){c.pop=Math.min(12,c.pop+1);}const army=s.units.filter(u=>u.owner===c.owner);const hostile=this.isWar(c.owner);if(s.turn%(c.owner==='persia'?5:8)===0&&army.length<(c.owner==='persia'?7:3)){const tier=Math.min(this.era(),Math.floor(s.turn/30));const type=tier>=4?'rifle':tier>=3?'musket':tier>=2?(s.turn%2?'crossbow':'pikeman'):s.turn>15?(s.turn%2?'swordsman':'archer'):'warrior';this.spawnNear(type,c.owner,c.tile);}
if(hostile){const targets=s.units.filter(u=>u.owner==='greece'&&distance(this.at(c.tile),this.at(u.tile))<=2);if(targets.length){targets[0].hp-=25;if(targets[0].hp<=0)s.units=s.units.filter(u=>u.id!==targets[0].id);}}
}
if(s.turn===22&&!this.isWar('persia')){s.wars.push('persia');this.log('大流士一世宣战！波斯军队开始向希腊进军。','war');}
if(s.turn%12===0)for(const t of s.tiles.filter(t=>t.camp))if(s.units.filter(u=>u.owner==='barbarian').length<7)this.spawnNear(s.turn>30?'archer':'warrior','barbarian',t.id);
for(const u of [...s.units.filter(u=>u.owner!=='greece')]){if(!this.unit(u.id))continue;u.moves=UNITS[u.type].moves;u.attacked=false;if(!this.isWar(u.owner))continue;const t=this.at(u.tile);let foes=s.units.filter(v=>v.owner==='greece');let cities=this.owned();let target=[...foes,...cities].sort((a,b)=>distance(t,this.at(a.tile))-distance(t,this.at(b.tile)))[0];if(!target)continue;const range=UNITS[u.type].range||1;let dist=distance(t,this.at(target.tile));const aggro=u.owner==='persia'?50:u.owner==='barbarian'?6:6;if(dist>aggro)continue;const home=this.s.cities.find(c=>c.owner===u.owner);if(home&&!['persia','barbarian'].includes(u.owner)&&distance(this.at(home.tile),this.at(target.tile))>3)continue;if(u.hp<30&&distance(t,this.at(target.tile))>1){u.hp+=15;continue;}
const path=this.aiPath(u,target);for(const next of path){if(u.moves<=0)break;const cost=this.stepCost(u,this.at(u.tile),next,u.moves);u.tile=next.id;u.moves-=cost;dist=distance(next,this.at(target.tile));if(dist<=range)break;}

if(dist<=range&&u.moves>0)this.attack(u,target,!!target.buildings,true);
}}
aiPath(u,target){const start=this.at(u.tile),goal=this.at(target.tile),range=UNITS[u.type].range||1;const open=[start],cost=new Map([[start.id,0]]),previous=new Map();let found=null;while(open.length){open.sort((a,b)=>(cost.get(a.id)+distance(a,goal))-(cost.get(b.id)+distance(b,goal)));const t=open.shift();if(distance(t,goal)<=range){found=t;break;}for(const n of this.neighbors(t)){if(n.terrain==='mountain'||TERRAIN[n.terrain].water&&!(u.owner==='persia'&&this.s.turn>25)||this.s.units.some(v=>v.id!==u.id&&v.tile===n.id)||this.cityAt(n.id)&&n.id!==start.id)continue;const nc=cost.get(t.id)+(TERRAIN[n.terrain].cost||1);if(cost.has(n.id)&&cost.get(n.id)<=nc)continue;cost.set(n.id,nc);previous.set(n.id,t.id);if(!open.some(v=>v.id===n.id))open.push(n);}}
const path=[];while(found&&found.id!==start.id){path.unshift(found);found=this.at(previous.get(found.id));}return path;}

vote(){if(!this.has('printing'))return this.fail('需要先研究印刷术，召开城邦大会。');const allies=Object.entries(this.s.influence).filter(([id,v])=>v>=60&&!this.isWar(id)&&this.s.cities.some(c=>c.owner===id)).length;if(allies<3)return this.fail('外交胜利需要至少 3 个城邦盟友。');this.win('外交胜利','城邦大会推举亚历山大为世界领袖。希腊同盟迎来共同的和平。');this.emit();return true;}
score(){return this.owned().reduce((n,c)=>n+50+c.pop*10+c.buildings.length*5,0)+this.s.techs.length*8+this.s.policies.length*10+Object.values(this.s.influence).filter(v=>v>=60).length*30;}
win(title,detail,won=true){if(!this.s.victory)this.s.victory={title,detail,won,score:this.score()};}
serialize(){return JSON.stringify(this.s);}
}
