import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {TERRAIN,FACTIONS,UNITS,RESOURCES} from './data.js';
import {W,H,seeded,distance} from './engine.js';
import {icon} from './icons.js';
export const position=t=>new THREE.Vector3(Math.sqrt(3)*(t.q+t.r/2),t.height,1.5*t.r);
const geo={hex:new THREE.CylinderGeometry(1,1,1,6),box:new THREE.BoxGeometry(1,1,1),cone:new THREE.ConeGeometry(1,1,6),sphere:new THREE.IcosahedronGeometry(1,0),cyl:new THREE.CylinderGeometry(1,1,1,8),roof:new THREE.CylinderGeometry(1,1,1,3),ring:new THREE.TorusGeometry(.38,.025,5,12)};
class Batch{
constructor(scene){this.scene=scene;this.buckets=new Map();this.meshes=[];this.dummy=new THREE.Object3D();}
add(shape,color,pos,scale,rotation=[0,0,0],tile=null,tech=null){const key=shape+'-'+color;let b=this.buckets.get(key);if(!b){b={shape,color,items:[]};this.buckets.set(key,b);}this.dummy.position.set(...pos);this.dummy.rotation.set(...rotation);this.dummy.scale.set(...scale);this.dummy.updateMatrix();b.items.push({matrix:this.dummy.matrix.clone(),tile,tech});}
finish(){for(const b of this.buckets.values()){const mat=new THREE.MeshStandardMaterial({color:b.color,roughness:.92,flatShading:true});const mesh=new THREE.InstancedMesh(geo[b.shape],mat,b.items.length);b.items.forEach((it,i)=>mesh.setMatrixAt(i,it.matrix));mesh.castShadow=true;mesh.receiveShadow=true;mesh.userData.items=b.items;mesh.frustumCulled=false;this.scene.add(mesh);this.meshes.push(mesh);}}
visibility(tiles,techs=[]){const zero=new THREE.Matrix4().makeScale(0,0,0);for(const mesh of this.meshes){mesh.userData.items.forEach((it,i)=>{mesh.setMatrixAt(i,(it.tile===null||tiles[it.tile].explored)&&(!it.tech||techs.includes(it.tech))?it.matrix:zero);mesh.setColorAt(i,new THREE.Color(it.tile===null||tiles[it.tile].visible?0xffffff:0x64727a));});mesh.instanceMatrix.needsUpdate=true;if(mesh.instanceColor)mesh.instanceColor.needsUpdate=true;}}
clear(){for(const m of this.meshes){this.scene.remove(m);m.material.dispose();}this.meshes=[];this.buckets.clear();}}
export class World{
constructor(container,game,onTile,onHover){this.el=container;this.game=game;this.onTile=onTile;this.onHover=onHover;this.scene=new THREE.Scene();this.scene.background=new THREE.Color('#183544');this.scene.fog=new THREE.FogExp2('#183544',.006);this.renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));this.renderer.setSize(innerWidth,innerHeight);this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.25;this.el.appendChild(this.renderer.domElement);this.camera=new THREE.PerspectiveCamera(36,innerWidth/innerHeight,.1,220);this.controls=new OrbitControls(this.camera,this.renderer.domElement);this.controls.enableDamping=true;this.controls.dampingFactor=.075;this.controls.minDistance=9;this.controls.maxDistance=68;this.controls.minPolarAngle=.2;this.controls.maxPolarAngle=Math.PI*.43;this.controls.mouseButtons={LEFT:THREE.MOUSE.PAN,MIDDLE:THREE.MOUSE.DOLLY,RIGHT:THREE.MOUSE.ROTATE};this.controls.touches={ONE:THREE.TOUCH.PAN,TWO:THREE.TOUCH.DOLLY_ROTATE};this.controls.maxTargetRadius=40;
this.scene.add(new THREE.HemisphereLight(0xe3f4ff,0x526846,2.1));const sun=new THREE.DirectionalLight(0xffe1ac,3);sun.position.set(-8,32,10);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-30;sun.shadow.camera.right=30;sun.shadow.camera.top=30;sun.shadow.camera.bottom=-30;sun.shadow.camera.far=90;sun.shadow.normalBias=.04;sun.target.position.set(18,0,14);this.scene.add(sun,sun.target);const fill=new THREE.DirectionalLight(0xa4dced,.6);fill.position.set(35,15,-15);this.scene.add(fill);
this.static=new Batch(this.scene);this.dynamic=new Batch(this.scene);this.tiles=[];this.tileMeshes=[];this.labels=document.getElementById('map-labels');this.labelsState=[];this.raycaster=new THREE.Raycaster();this.pointer=new THREE.Vector2();this.hovered=null;this.selected=null;this.reachable=new Set();this.highlight=new THREE.Group();this.scene.add(this.highlight);this.gridVisible=false;this.makeMap();this.home(true);this.update();
const cv=this.renderer.domElement;let down=null;cv.addEventListener('pointerdown',e=>{down={x:e.clientX,y:e.clientY,time:performance.now()};});cv.addEventListener('pointerup',e=>{if(down&&Math.hypot(e.clientX-down.x,e.clientY-down.y)<7&&e.button===0){const t=this.pick(e);if(t)this.onTile(t);}down=null;});cv.addEventListener('pointermove',e=>{if(down&&Math.hypot(e.clientX-down.x,e.clientY-down.y)>8){this.onHover(null);return;}const t=this.pick(e);this.hovered=t;this.onHover(t,e.clientX,e.clientY);});cv.addEventListener('pointerleave',()=>this.onHover(null));cv.addEventListener('contextmenu',e=>e.preventDefault());window.addEventListener('resize',()=>this.resize());this.animate();}
makeMap(){const s=this.game.s,rand=seeded(s.seed);const terrainGeo=new THREE.CylinderGeometry(.995,.995,.35,6);const terrainMat=new THREE.MeshStandardMaterial({roughness:1,flatShading:true});this.ground=new THREE.InstancedMesh(terrainGeo,terrainMat,s.tiles.length);this.ground.receiveShadow=true;const o=new THREE.Object3D();const edges=[];
for(const t of s.tiles){const p=position(t);o.position.set(p.x,p.y-.2,p.z);o.updateMatrix();this.ground.setMatrixAt(t.id,o.matrix);this.tiles.push(p);const water=TERRAIN[t.terrain].water,coastal=!water&&this.game.neighbors(t).some(n=>TERRAIN[n.terrain].water);if(coastal)this.static.add('hex',0xc6b58c,[p.x,p.y-.21,p.z],[1.012,.16,1.012],[0,0,0],t.id);
const add=(sh,col,x,y,z,sx,sy,sz,ry=0,tech=null)=>this.static.add(sh,col,[p.x+x,p.y+y,p.z+z],[sx,sy,sz],[0,ry,0],t.id,tech);
if(t.terrain==='forest'){for(let j=0;j<5+Math.floor(rand()*4);j++){const x=(rand()-.5)*1.35,z=(rand()-.5)*1.3,sz=.7+rand()*.5;add('cyl',0x69523b,x,.2,z,.035,.5,.035);if(rand()<.55){add('cone',rand()<.5?0x315b46:0x466e45,x,.57*sz,z,.28*sz,.8*sz,.28*sz);add('cone',0x527d4b,x,.83*sz,z,.2*sz,.6*sz,.2*sz);}else{add('sphere',rand()<.5?0x648550:0x4f7847,x,.55*sz,z,.3*sz,.4*sz,.3*sz,rand());}}}
if(t.terrain==='mountain'){for(let j=0;j<3;j++){const x=(j-1)*.38,z=(rand()-.5)*.6,h=1.4+rand()*1.5;add('cone',j===1?0x9e9e8b:0x838978,x,h/2,z,.6,h,.58,rand());add('cone',0xe5e8d7,x,h*.88,z,.19,h*.29,.19,rand());}}
if(t.terrain==='hill'){add('sphere',0xa1a077,0,.08,0,.85,.4,.8,rand());for(let j=0;j<3;j++)add('sphere',0x8c9174,(rand()-.5),.14,(rand()-.5),.3,.26,.3,rand());}
if(['grass','plains','tundra'].includes(t.terrain)&&rand()<.4){for(let j=0;j<5;j++)add('cone',t.terrain==='plains'?0xc1b978:0x86965e,(rand()-.5)*1.5,.09,(rand()-.5)*1.3,.025,.18,.04,rand());}
if(t.resource==='wheat'){for(let j=0;j<15;j++)add('box',0xd4ba66,(j%5-2)*.17,.15,(Math.floor(j/5)-1)*.2,.04,.3,.04);}
if(['iron','gold','marble'].includes(t.resource)){for(let j=0;j<4;j++)add('sphere',t.resource==='gold'?0xc5a957:t.resource==='iron'?0x5f6d72:0xdfded0,(rand()-.5)*.8,.21,(rand()-.5)*.8,.19,.23,.18,rand(),RESOURCES[t.resource].tech||null);}
if(t.resource==='wine'||t.resource==='silk'){for(let j=0;j<3;j++){add('box',0x655142,(j-1)*.3,.13,0,.03,.3,1);for(let k=0;k<3;k++)add('sphere',t.resource==='wine'?0x657441:0x79954f,(j-1)*.3,.28,(k-1)*.3,.13,.18,.18);}}
if(t.resource==='horses'){for(let j=0;j<2;j++){const x=(j-.5)*.55;add('box',0x825e43,x,.27,0,.16,.22,.38,0,'husbandry');add('cone',0x946d4a,x,.45,-.2,.09,.3,.1,.2,'husbandry');for(const a of[-.06,.06])for(const z of[-.13,.13])add('box',0x684a37,x+a,.1,z,.04,.24,.04,0,'husbandry');}}
if(t.resource==='fish'){for(let j=0;j<3;j++)add('sphere',0x89c7c1,(rand()-.5),.025,(rand()-.5),.1,.035,.21,rand()*6);}
for(let i=0;i<6;i++){const a=i*Math.PI/3,b=(i+1)*Math.PI/3;edges.push(p.x+Math.sin(a),p.y-.011,p.z+Math.cos(a),p.x+Math.sin(b),p.y-.011,p.z+Math.cos(b));}}
this.scene.add(this.ground);this.static.finish();const gg=new THREE.BufferGeometry();gg.setAttribute('position',new THREE.Float32BufferAttribute(edges,3));this.grid=new THREE.LineSegments(gg,new THREE.LineBasicMaterial({color:0xd7e8d0,transparent:true,opacity:.16,depthWrite:false}));this.grid.visible=false;this.scene.add(this.grid);
const sea=new THREE.Mesh(new THREE.PlaneGeometry(300,300),new THREE.MeshStandardMaterial({color:0x214f65,roughness:.65,metalness:.15}));sea.rotation.x=-Math.PI/2;sea.position.set(20,-.45,15);this.scene.add(sea);}
update(){const s=this.game.s;for(const t of s.tiles){let col=new THREE.Color(TERRAIN[t.terrain].color);if(!t.explored)col.setHex(0x24414d);else if(!t.visible)col.multiplyScalar(.53);else col.multiplyScalar(.96+seeded(t.id+97)()*.12);this.ground.setColorAt(t.id,col);}this.ground.instanceColor.needsUpdate=true;this.static.visibility(s.tiles,s.techs);this.dynamic.clear();
for(const t of s.tiles){if(!t.explored)continue;const p=position(t);const add=(sh,col,x,y,z,sx,sy,sz,ry=0)=>this.dynamic.add(sh,col,[p.x+x,p.y+y,p.z+z],[sx,sy,sz],[0,ry,0],t.id);
if(t.improvement==='farm'){add('hex',0xb6a65a,0,.01,0,.75,.05,.75);for(let j=0;j<6;j++)add('box',j%2?0xd0bd6b:0x82724a,(j-2.5)*.2,.055,0,.06,.065,1.1);}
if(t.improvement==='mine'||t.improvement==='quarry'){add('box',0x74634c,0,.4,0,.5,.5,.2);add('box',0x342f27,0,.42,-.13,.28,.32,.035);add('roof',0x88775b,0,.71,0,.44,.36,.45,Math.PI/2);}
if(t.improvement==='pasture'){for(let j=0;j<6;j++){const a=j*Math.PI/3;add('box',0xb4a074,Math.sin(a)*.74,.18,Math.cos(a)*.74,.035,.36,.035);}add('hex',0xa9a777,0,.01,0,.4,.02,.4);}
if(t.improvement==='plantation')for(let j=0;j<4;j++)add('sphere',0x7d9442,(j%2-.5)*.5,.32,(Math.floor(j/2)-.5)*.5,.2,.3,.2);
if(t.road)add('box',0xc7b58e,0,.027,0,.22,.04,1.65,.5);
if(t.ruin){for(let j=0;j<4;j++)add('cyl',0xc6bda2,(j%2-.5)*.55,.2,(Math.floor(j/2)-.5)*.5,.08,j===1?.55:.35,.08);add('box',0xc5bba1,0,.05,0,.9,.1,.8);}
if(t.camp){add('cone',0x97694d,0,.36,0,.5,.7,.43);add('cyl',0x432d23,.42,.5,0,.025,1,.025);add('box',0xc25442,.59,.86,0,.3,.25,.025);}
if(t.owner){const col=FACTIONS[t.owner].hex;for(let i=0;i<6;i++){const angle=i*Math.PI/3,dx=Math.sin(angle+Math.PI/6)*1.73,dz=Math.cos(angle+Math.PI/6)*1.73;const near=s.tiles.find(n=>Math.abs(position(n).x-p.x-dx)<.1&&Math.abs(position(n).z-p.z-dz)<.1);if(!near||near.owner!==t.owner){const a=angle,b=(i+1)*Math.PI/3;const pa=new THREE.Vector3(p.x+Math.sin(a)*.97,p.y+.035,p.z+Math.cos(a)*.97),pb=new THREE.Vector3(p.x+Math.sin(b)*.97,p.y+.035,p.z+Math.cos(b)*.97);const mid=pa.clone().add(pb).multiplyScalar(.5);this.dynamic.add('box',col,mid.toArray(),[.047,.055,pa.distanceTo(pb)],[0,Math.atan2(pb.x-pa.x,pb.z-pa.z),0],t.id);}}}}
for(const c of s.cities){const t=this.game.at(c.tile);if(!t.explored)continue;this.cityModel(c);}
for(const u of s.units){const t=this.game.at(u.tile);if(u.owner!=='greece'&&!t.visible)continue;this.unitModel(u);}
this.dynamic.finish();this.dynamic.visibility(s.tiles,s.techs);this.makeLabels();this.drawMinimap();this.select(this.selected);if(s.lastCombat&&s.lastCombat.id!==this.combatSeen){this.combatSeen=s.lastCombat.id;const t=this.game.at(s.lastCombat.tile);if(t.visible){const el=document.createElement('div');el.className='combat-float';el.textContent='−'+s.lastCombat.dealt;document.getElementById('game').append(el);const p=position(t).add(new THREE.Vector3(0,1.4,0)).project(this.camera);el.style.left=(p.x+1)/2*innerWidth+'px';el.style.top=(-p.y+1)/2*innerHeight+'px';setTimeout(()=>el.remove(),1400);}}}
cityModel(c){const t=this.game.at(c.tile),p=position(t),rand=seeded(c.id);const col=FACTIONS[c.owner].hex;const add=(sh,color,x,y,z,sx,sy,sz,ry=0)=>this.dynamic.add(sh,color,[p.x+x,p.y+y,p.z+z],[sx,sy,sz],[0,ry,0],t.id);add('hex',0xb8af8e,0,.035,0,.92,.08,.92);add('box',0xe5d8ad,0,.11,0,.8,.13,.7);add('box',0xddd2af,0,.19,0,.69,.07,.57);for(const x of[-.26,-.09,.09,.26])for(const z of[-.2,.2]){add('cyl',0xe8e0c4,x,.4,z,.037,.39,.037);add('box',0xe9dfc0,x,.62,z,.1,.045,.1);}add('box',0xdcd0a8,0,.65,0,.77,.07,.57);add('roof',c.owner==='persia'?0xb68b65:0xb88860,0,.77,0,.47,.8,.18,Math.PI/2);
for(let j=0;j<Math.min(14,5+c.pop);j++){let a=j*2.4,r=.48+rand()*.23,x=Math.cos(a)*r,z=Math.sin(a)*r,h=.12+rand()*.18;add('box',j%2?0xe0d3aa:0xcfc5a0,x,h/2+.1,z,.18,h,.19);add('roof',j%2?0xab7155:0xbd8865,x,h+.13,z,.15,.22,.09,Math.PI/2);}
if(c.buildings.includes('walls')||c.buildings.includes('castle'))for(let i=0;i<6;i++){const a=i*Math.PI/3;add('box',0xbab298,Math.sin(a)*.88,.25,Math.cos(a)*.88,.5,.45,.1,-a);}
add('cyl',0xa59264,-.38,.65,.2,.018,1.15,.018);add('box',col,-.25,1.12,.2,.27,.26,.025);
if(c.buildings.some(id=>['pyramids','greatlibrary','gardens'].includes(id)))add('cone',0xdfc186,.7,.45,-.6,.32,.8,.32);}
unitModel(u){const t=this.game.at(u.tile),p=position(t),d=UNITS[u.type],team=FACTIONS[u.owner].hex;const add=(sh,color,x,y,z,sx,sy,sz,ry=0)=>this.dynamic.add(sh,color,[p.x+x,p.y+y,p.z+z],[sx,sy,sz],[0,ry,0],t.id);const offset=this.game.cityAt(u.tile)?-.55:0;
if(d.naval){add('sphere',0x714f36,0,.09,0,.28,.22,.68);add('cyl',0xa58b56,0,.6,0,.026,.9,.026);add('box',0xe6debf,.15,.62,0,.55,.63,.023);for(let j=0;j<5;j++){add('box',0xb49a61,-.38,.07,(j-2)*.2,.45,.03,.035,-.5);add('box',0xb49a61,.38,.07,(j-2)*.2,.45,.03,.035,.5);}return;}
if(u.type==='tank'){add('box',0x43564d,0,.28,0,.6,.35,.85);add('box',0x263833,-.33,.16,0,.16,.23,.95);add('box',0x263833,.33,.16,0,.16,.23,.95);add('box',team,0,.53,0,.39,.24,.38);add('box',0x5c6b52,0,.56,-.5,.07,.07,.72);return;}
if(d.flying){add('box',0xc5c9ba,0,1,0,.15,.14,.94);add('box',team,0,1,0,1.25,.045,.22);add('box',0xc5c9ba,0,1,.35,.5,.045,.17);return;}
if(d.siege){add('box',0x715239,0,.23,0,.46,.18,.7);for(const x of[-.28,.28])for(const z of[-.22,.22])add('cyl',0x493c2d,x,.2,z,.18,.07,.18);add('box',0x947347,0,.52,0,.09,.7,.09,.3);return;}
for(let j=0;j<(d.civilian?2:3);j++){const x=(j-1)*.31,z=j===1?-.15:.09,base=d.mounted?.4:0;if(d.mounted){add('box',0x825c3e,x,.3,z,.2,.3,.43);add('cone',0x946747,x,.5,z-.24,.1,.38,.14);for(const a of[-.07,.07])for(const b of[-.14,.14])add('box',0x755235,x+a,.13,z+b,.04,.27,.04);}
add('box',d.civilian?0xd7cbaa:team,x,base+.32,z,.16,.24,.12);add('sphere',0xd4b181,x,base+.52,z,.095,.105,.085);if(!d.civilian){add('sphere',0xb59a5b,x,base+.565,z,.105,.085,.092);add('box',team,x,base+.63,z,.025,.07,.14);add('sphere',0xb69a62,x-.12,base+.32,z-.06,.12,.16,.045);add('cyl',0x7d673f,x+.12,base+.42,z,.014,.86,.014);add('cone',0xb9bdac,x+.12,base+.91,z,.03,.12,.03);}else{add('box',0x84633f,x+.13,base+.31,z,.03,.6,.025,.15);}for(const a of[-.045,.045])add('box',0xa28e6c,x+a,base+.13,z,.035,.16,.045);}}
makeLabels(){this.labels.innerHTML='';this.labelsState=[];const s=this.game.s;const add=(html,p,cl,action)=>{const el=document.createElement('button');el.className=cl;el.innerHTML=html;el.addEventListener('pointerdown',e=>e.stopPropagation());el.addEventListener('click',e=>{e.stopPropagation();action();});this.labels.append(el);this.labelsState.push({el,p});return el;};for(const c of s.cities){const t=this.game.at(c.tile);if(!t.explored)continue;const p=position(t).add(new THREE.Vector3(0,1.8,0));const el=add(`<span class="city-pop">${c.pop}</span><span>${c.capital?'<i>★</i> ':''}${c.name}</span>${icon('chevron')}<span class="city-life"><b style="width:${c.hp/c.maxHp*100}%"></b></span>`,p,`city-marker ${c.owner==='greece'?'ours':''}`,()=>this.onTile(t,{city:c.id}));el.style.setProperty('--faction',FACTIONS[c.owner].color);el.setAttribute('aria-label',`查看${c.name}`);}
for(const u of s.units){const t=this.game.at(u.tile);if(u.owner!=='greece'&&!t.visible)continue;const p=position(t).add(new THREE.Vector3(.08,1.1,0));const el=add(`${icon(UNITS[u.type].icon)}<span class="unit-health"><b style="width:${u.hp}%"></b></span>`,p,`unit-marker ${u.owner==='greece'?'ours':'enemy'} ${this.selected===u.id?'selected':''} ${u.moves===0?'spent':''}`,()=>this.onTile(t,{unit:u.id}));el.style.setProperty('--faction',FACTIONS[u.owner].color);el.dataset.unit=u.id;el.setAttribute('aria-label',`${FACTIONS[u.owner].name}${UNITS[u.type].name}`);}}
select(id){this.selected=id;while(this.highlight.children.length){const m=this.highlight.children[0];this.highlight.remove(m);m.geometry?.dispose();m.material?.dispose();}const u=this.game.unit(id);this.reachable=u&&u.owner==='greece'?new Set(this.game.reachable(u).keys()):new Set();const outline=(t,color,opacity=1,fill=false)=>{const p=position(t);if(fill){const m=new THREE.Mesh(new THREE.CircleGeometry(.92,6),new THREE.MeshBasicMaterial({color,transparent:true,opacity,depthWrite:false,side:THREE.DoubleSide}));m.rotation.x=-Math.PI/2;m.rotation.z=Math.PI/6;m.position.set(p.x,p.y+.02,p.z);this.highlight.add(m);}else{const verts=[];for(let i=0;i<=6;i++){let a=i*Math.PI/3;verts.push(p.x+Math.sin(a)*.95,p.y+.09,p.z+Math.cos(a)*.95);}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(verts,3));this.highlight.add(new THREE.Line(g,new THREE.LineBasicMaterial({color,transparent:true,opacity})));}};if(u){for(const id of this.reachable){outline(this.game.at(id),0x8cd8ed,.32);outline(this.game.at(id),0x72c7dc,.09,true);}outline(this.game.at(u.tile),0xf4db8a,1);outline(this.game.at(u.tile),0xf4db8a,.18,true);if(u.owner==='greece'&&u.moves>0)for(const e of this.game.s.units.filter(e=>this.game.isWar(e.owner)&&this.game.at(e.tile).visible&&distance(this.game.at(u.tile),this.game.at(e.tile))<=(UNITS[u.type].range||1)))outline(this.game.at(e.tile),0xf57b5c,.9);}
for(const l of this.labelsState)if(l.el.classList.contains('unit-marker'))l.el.classList.toggle('selected',Number(l.el.dataset.unit)===id);}
pick(e){this.pointer.set(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1);this.raycaster.setFromCamera(this.pointer,this.camera);const hit=this.raycaster.intersectObject(this.ground)[0];return hit?this.game.at(hit.instanceId):null;}
focus(tile,instant=false){const p=position(this.game.at(tile));const delta=p.clone().sub(this.controls.target);this.controls.target.copy(p);this.camera.position.add(delta);this.controls.update();}
home(){const c=this.game.owned()[0]||this.game.s.cities[0],p=position(this.game.at(c.tile));this.controls.target.set(p.x+1,0,p.z+.8);this.camera.position.set(p.x+7,19,p.z+20);this.controls.update();}
zoom(amount){const offset=this.camera.position.clone().sub(this.controls.target);offset.multiplyScalar(amount);offset.clampLength(this.controls.minDistance,this.controls.maxDistance);this.camera.position.copy(this.controls.target).add(offset);}
rotate(a){const offset=this.camera.position.clone().sub(this.controls.target);offset.applyAxisAngle(new THREE.Vector3(0,1,0),a);this.camera.position.copy(this.controls.target).add(offset);}
toggleGrid(){this.gridVisible=!this.gridVisible;this.grid.visible=this.gridVisible;return this.gridVisible;}
resize(){this.camera.aspect=innerWidth/innerHeight;this.camera.updateProjectionMatrix();this.renderer.setSize(innerWidth,innerHeight);}
drawMinimap(){const canvas=document.getElementById('minimap');if(!canvas)return;const ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);ctx.fillStyle='#142b38';ctx.fillRect(0,0,w,h);const sx=w/(W+1),sy=h/H;for(const t of this.game.s.tiles){ctx.fillStyle=!t.explored?'#263b40':t.owner?FACTIONS[t.owner].color:'#'+new THREE.Color(TERRAIN[t.terrain].color).getHexString();ctx.globalAlpha=t.visible||!t.explored?1:.55;ctx.fillRect((t.c+(t.r%2)/2)*sx,t.r*sy,sx+.5,sy+.5);}ctx.globalAlpha=1;for(const c of this.game.s.cities){const t=this.game.at(c.tile);if(!t.explored)continue;ctx.fillStyle='#fff1c8';ctx.beginPath();ctx.arc((t.c+.5)*sx,(t.r+.5)*sy,2.5,0,Math.PI*2);ctx.fill();}}
animate(){requestAnimationFrame(()=>this.animate());this.controls.update();for(const label of this.labelsState){const p=label.p.clone().project(this.camera);const x=(p.x+1)/2*innerWidth,y=(-p.y+1)/2*innerHeight;const visible=p.z<1&&x>-60&&x<innerWidth+60&&y>60&&y<innerHeight-60;label.el.style.display=visible?'':'none';if(visible)label.el.style.transform=`translate(${x}px,${y}px) translate(-50%,-50%)`;}this.renderer.render(this.scene,this.camera);}
}
