import * as T from 'three';
import {PointerLockControls} from 'three/addons/controls/PointerLockControls.js';
import {SHIPS,buildShip,SPEED_PER_KNOT} from './ships.js';
import {MAP_HALF_SIZE,CAPTURE_ZONES,fleetDeployment,hullTouchesLand,battleCourse,navigate} from './battlefield.js';
import {Effects,audio} from './effects.js';
import {clamp,angleDiff,distance,segmentCircle,hitShip,armorHit,captureStep} from './mechanics.js';
const $=s=>document.querySelector(s),TAU=Math.PI*2;
const V=(x=0,y=0,z=0)=>new T.Vector3(x,y,z);
const throttleNames=['全速倒车','停车','¼ 航速','½ 航速','¾ 航速','全速前进'];
export class Battle{
 constructor({scene,camera,renderer,water,islands,selected,onExit}){Object.assign(this,{scene,camera,renderer,water,islands,selected,onExit});this.effects=new Effects(scene);this.group=new T.Group();scene.add(this.group);this.entities=[];this.shells=[];this.torpedoes=[];this.smokes=[];this.keys=new Set();this.time=0;this.seconds=600;this.score=[300,300];this.damage=0;this.hits=0;this.kills=0;this.shots=0;this.finished=false;this.ammo=selected==='shimakaze'?'HE':'AP';this.throttle=4;this.rudder=0;this.lockRudder=0;this.scope=false;this.zoom=205;this.viewYaw=Math.PI;this.lookCamera=new T.PerspectiveCamera();this.lookCamera.rotation.set(-.07,0,0,'YXZ');this.mouseInput=matchMedia('(pointer:fine)').matches;this.pointer=new T.Vector2(0,0);this.aim=V(0,4,-600);this.fireHeld=false;this.lastFire=0;this.uiTime=0;this.shake=0;this.track=false;this.mapOpen=false;this.scoreOpen=false;this.torpWide=false;this.difficulty=$('#difficulty').value;this.hitNotice='';this.hitUntil=0;this.statusTimer=0;this.capNames=['A','B','C'];
 for(const entry of fleetDeployment(selected)){const e=this.spawn(entry.id,entry.team,entry.x,entry.z,entry.heading,entry.player);e.lane=entry.lane;e.flank=entry.flank;if(entry.player)this.player=e;}
 this.player.torpCool=0;this.player.torpBanks=[0,0,0];
 this.caps=CAPTURE_ZONES.map((c,i)=>({...c,owner:-1,progress:0,contested:false,name:this.capNames[i]}));for(const c of this.caps){const g=new T.RingGeometry(207,210,90),m=new T.Mesh(g,new T.MeshBasicMaterial({color:0xd8cfad,transparent:true,opacity:.4,side:T.DoubleSide,depthWrite:false}));m.rotation.x=-Math.PI/2;m.position.set(c.x,.8,c.z);this.group.add(m);c.mesh=m;}
 this.consumables={repair:{key:'R',name:'损害管制',cool:0,active:0,count:Infinity,duration:10,cooldown:55},heal:{key:'T',name:selected==='shimakaze'?'烟幕发生器':'维修小组',cool:0,active:0,count:3,duration:selected==='shimakaze'?22:20,cooldown:65},boost:{key:'Y',name:selected==='shimakaze'?'引擎增压':selected==='bismarck'?'水下搜索':'侦察机',cool:0,active:0,count:2,duration:35,cooldown:80}};
 this.createUI();this.bind();this.lockTarget(this.entities.find(u=>u.team===1&&u.id==='iowa'));this.message('全舰战斗部署！移动鼠标瞄准，A / D 转舵，X 切换目标。');audio.start();$('#sound-btn').textContent='♫';$('#sound-btn').setAttribute('aria-label','关闭声音');this.updateHUD();}
 spawn(id,team,x,z,heading,player=false){const spec=SHIPS[id],mesh=buildShip(id);mesh.position.set(x,0,z);mesh.rotation.y=heading;this.group.add(mesh);const entity={id,team,x,z,heading,spec,mesh,hp:spec.hp,speed:spec.knots*SPEED_PER_KNOT*.5,rudder:0,player,dead:0,cool:spec.torps?4:6+Math.random()*7,fire:0,flood:0,immune:0,heal:0,torpCool:15+Math.random()*15,secCool:2,aiPhase:Math.random()*TAU,target:null,detected:0,disabled:0,turretCool:mesh.userData.turrets.map(()=>0),turretAim:mesh.userData.turrets.map(t=>t.rotation.y),wake:0,repairable:0};this.entities.push(entity);return entity;}
 createUI(){const ui=$('#battle-ui');ui.hidden=false;ui.innerHTML=`<div class="battle-score"><div id="team-icons"></div><div class="score-row"><strong id="blue-score">300</strong><div class="cap-row"><span id="cap-A">A</span><span id="cap-B">B</span><span id="cap-C">C</span></div><strong id="red-score">300</strong></div><div class="battle-timer" id="battle-timer">10:00</div></div><div class="mission">群岛交锋 <span>制海权争夺</span></div><div class="damage-panel"><span>造成伤害</span><strong id="damage-count">0</strong><small id="hit-count">命中 0 · 击沉 0</small></div><div id="unit-labels"></div><div id="reticle"><span></span><div id="aim-range">0.0 km</div></div><div id="lead-marker" hidden title="目标提前量参考">＋</div><div id="target-panel"></div><div id="hit-notice"></div><div id="threat-status"></div><div class="ship-hud"><div class="hud-ship">${this.player.spec.tier} <span>${this.player.spec.name}</span><small>${this.player.spec.type}</small></div><div class="hp-track"><div id="hp-bar"></div><div id="heal-bar"></div></div><div id="hp-text"></div><div class="speed-read"><strong id="speed-read">0.0</strong><span>kn</span><div id="throttle-read">¾ 航速</div></div><div class="throttle-controls"><button data-key="s">S −</button><div id="throttle-bars"></div><button data-key="w">W +</button></div><div class="rudder-read"><span>左舵</span><div><i id="rudder-needle"></i></div><span>右舵</span></div><div id="ship-status"></div></div><div class="armament"><div id="turret-status"></div><div class="ammo-slots"><button data-ammo="HE"><kbd>1</kbd><b>HE</b><small>高爆弹</small></button><button data-ammo="AP"><kbd>2</kbd><b>AP</b><small>穿甲弹</small></button><button data-ammo="TORP" ${this.player.spec.torps?'':'disabled'}><kbd>3</kbd><b>Ⅲ</b><small>鱼雷</small></button><i></i>${Object.entries(this.consumables).map(([id,c])=>`<button data-consumable="${id}"><kbd>${c.key}</kbd><b>${id==='repair'?'✚':id==='heal'?'▥':'⌁'}</b><small>${c.name}</small><em></em></button>`).join('')}</div><div class="battle-help"><span><kbd>Shift</kbd> 望远镜</span><span><kbd>双击</kbd> 齐射</span><span><kbd>X</kbd> 锁定</span><span><kbd>F1</kbd> 指南</span></div></div><div class="minimap-wrap"><div><span>战术海图</span><button id="map-button">M ⤢</button></div><canvas id="minimap" width="280" height="280"></canvas><span class="minimap-scale">北太平洋 ／ ${MAP_HALF_SIZE*2/100} × ${MAP_HALF_SIZE*2/100} km</span></div><div id="battle-feed"></div><div class="battle-caption" id="battle-caption"></div><div id="compass"></div><div id="scoreboard" hidden></div><div class="touch-controls"><button data-touch="a">◀</button><button data-touch="d">▶</button><button id="touch-scope">瞄准</button><button id="touch-fire">开火</button></div><button class="battle-pause" id="battle-pause" aria-label="暂停战斗">Ⅱ</button>`;
 this.mini=$('#minimap').getContext('2d');this.labels=new Map();for(const e of this.entities){if(e.player)continue;const b=document.createElement('button');b.className='unit-label '+(e.team?'enemy':'ally');b.innerHTML=`<small>${e.spec.tier} ${e.spec.type}</small><strong>${e.spec.name}</strong><span class="label-hp"><i></i></span><em></em>`;b.onclick=()=>this.lockTarget(e);$('#unit-labels').appendChild(b);this.labels.set(e,b);}this.consumableEls={};for(const [id] of Object.entries(this.consumables))this.consumableEls[id]=$(`[data-consumable="${id}"]`);}
 bind(){
 this.abort=new AbortController();const opts={signal:this.abort.signal};this.listen=(el,event,fn,extra={})=>el.addEventListener(event,fn,{...opts,...extra});
 const canvas=this.renderer.domElement;
 this.mouseControls=new PointerLockControls(this.lookCamera,canvas);
 this.mouseControls.minPolarAngle=Math.PI/2-.45;this.mouseControls.maxPolarAngle=Math.PI/2+.65;
 this.mouseControls.addEventListener('change',()=>{this.track=false;});
 this.mouseControls.addEventListener('lock',()=>{if(this.finished||document.querySelector('dialog[open]'))document.exitPointerLock();});
 this.mouseControls.addEventListener('unlock',()=>{if(!this.finished&&!document.querySelector('dialog[open]'))this.openDialog('#pause-dialog');});
 this.listen(window,'keydown',e=>{
   const k=this.inputKey(e.key);
   if(!['w','s','a','d','q','e','1','2','3','r','t','y','x','z','m','p','f1','shift','tab','escape',' '].includes(k))return;
   e.preventDefault();if(!e.repeat)this.key(k);
   if(!this.finished&&!document.querySelector('dialog[open]'))this.keys.add(k);
 });
 this.listen(window,'keyup',e=>{this.keys.delete(this.inputKey(e.key));if(e.key==='Tab'){this.scoreOpen=false;$('#scoreboard').hidden=true;}});
 this.listen($('#result-dialog'),'cancel',e=>e.preventDefault());
 for(const id of ['pause','guide','settings'])this.listen($('#'+id+'-dialog'),'cancel',e=>{e.preventDefault();this.openDialog('#pause-dialog');});
 this.listen(window,'blur',()=>{if(!this.finished&&!document.querySelector('dialog[open]'))this.openDialog('#pause-dialog');});
 this.listen(document,'visibilitychange',()=>{if(document.hidden&&!this.finished&&!document.querySelector('dialog[open]'))this.openDialog('#pause-dialog');});
 this.listen(canvas,'pointerdown',e=>{
   if(this.finished||document.querySelector('dialog[open]'))return;
   if(e.pointerType==='touch'){this.touchLook={id:e.pointerId,x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);return;}
   if(e.button!==0)return;
   if(!this.mouseControls.isLocked){this.mouseInput=true;this.startMouseLook();return;}
   this.computeAim();this.fireHeld=true;this.fire(this.player,false);this.lastFire=this.time;
 });
 this.listen(canvas,'pointermove',e=>{
   if(e.pointerType!=='touch'||this.touchLook?.id!==e.pointerId||document.querySelector('dialog[open]'))return;
   const rotation=this.lookCamera.rotation,sensitivity=.003*this.camera.fov/50;
   rotation.y-=(e.clientX-this.touchLook.x)*sensitivity;rotation.x=clamp(rotation.x-(e.clientY-this.touchLook.y)*sensitivity,-.65,.45);
   this.touchLook.x=e.clientX;this.touchLook.y=e.clientY;this.track=false;
 });
 this.listen(window,'pointerup',e=>{if(e.button===0)this.fireHeld=false;if(this.touchLook?.id===e.pointerId)this.touchLook=null;});
 this.listen(canvas,'pointercancel',()=>{this.touchLook=null;this.fireHeld=false;});
 this.listen(canvas,'dblclick',e=>{if(e.button===0&&this.mouseControls.isLocked)this.fire(this.player,true);});
 this.listen(canvas,'contextmenu',e=>e.preventDefault());
 this.listen(canvas,'wheel',e=>{e.preventDefault();if(document.querySelector('dialog[open]'))return;if(this.scope)this.camera.fov=clamp(this.camera.fov+e.deltaY*.012,12,30);else this.zoom=clamp(this.zoom+e.deltaY*.15,130,390);},{passive:false});
 document.querySelectorAll('[data-ammo]').forEach(b=>b.onclick=()=>this.selectAmmo(b.dataset.ammo));document.querySelectorAll('[data-consumable]').forEach(b=>b.onclick=()=>this.useConsumable(b.dataset.consumable));document.querySelectorAll('[data-key]').forEach(b=>b.onclick=()=>this.key(b.dataset.key));
 document.querySelectorAll('[data-touch]').forEach(b=>{this.listen(b,'pointerdown',e=>{e.preventDefault();this.key(b.dataset.touch);this.keys.add(b.dataset.touch);b.setPointerCapture(e.pointerId);});this.listen(b,'pointerup',()=>this.keys.delete(b.dataset.touch));this.listen(b,'pointercancel',()=>this.keys.delete(b.dataset.touch));});
 $('#touch-fire').onclick=()=>this.fire(this.player,true);$('#touch-scope').onclick=()=>this.key('shift');$('#map-button').onclick=()=>this.key('m');$('#battle-pause').onclick=()=>this.key('escape');
 $('#resume-btn').onclick=()=>{$('#pause-dialog').close();this.startMouseLook();};
 $('#leave-btn').onclick=()=>{$('#pause-dialog').close();this.onExit();};$('#again-btn').onclick=()=>{$('#result-dialog').close();this.onExit();$('#battle-btn').click();};$('#result-port-btn').onclick=()=>{$('#result-dialog').close();this.onExit();};
 }
 inputKey(key){return ({ArrowLeft:'a',ArrowRight:'d',ArrowUp:'w',ArrowDown:'s'})[key]||key.toLowerCase();}
 async startMouseLook(){
   if(!this.mouseInput||this.finished||document.querySelector('dialog[open]'))return;
   this.mouseControls.enabled=true;
   try{await this.renderer.domElement.requestPointerLock();$('#pause-hint').textContent='移动鼠标控制视角与准星，Esc 暂停并释放鼠标。';}
   catch(error){console.warn('Mouse capture:',error.name,error.message);if(!this.finished){this.openDialog('#pause-dialog');$('#pause-hint').textContent='浏览器未允许控制鼠标。请在 Chrome 或 Edge 独立窗口打开游戏，允许鼠标控制后点击「继续战斗」。';}}
 }
 openDialog(selector){
   this.keys.clear();this.fireHeld=false;this.touchLook=null;this.scoreOpen=false;$('#scoreboard').hidden=true;
   this.mouseControls.enabled=false;
   const dialog=$(selector),open=document.querySelector('dialog[open]');if(open&&open!==dialog)open.close();if(!dialog.open)dialog.showModal();
   if(document.pointerLockElement===this.renderer.domElement)document.exitPointerLock();
 }
 key(k){if(k==='escape'){if(!this.finished)this.openDialog('#pause-dialog');return;}if(k==='f1'){if(!this.finished)this.openDialog('#guide-dialog');return;}if(document.querySelector('dialog[open]')||this.finished)return;if(k==='w')this.throttle=clamp(this.throttle+1,0,5);if(k==='s')this.throttle=clamp(this.throttle-1,0,5);if(k==='q')this.lockRudder=clamp(this.lockRudder+.5,-1,1);if(k==='e')this.lockRudder=clamp(this.lockRudder-.5,-1,1);if(k==='a'||k==='d')this.lockRudder=0;if(k==='1')this.selectAmmo('HE');if(k==='2')this.selectAmmo('AP');if(k==='3'){if(this.ammo==='TORP')this.torpWide=!this.torpWide;else this.selectAmmo('TORP');}if(k==='r')this.useConsumable('repair');if(k==='t')this.useConsumable('heal');if(k==='y')this.useConsumable('boost');if(k==='shift'){this.scope=!this.scope;const eye=this.cameraDestination();this.lookCamera.position.copy(eye);this.lookCamera.lookAt(this.aim);this.camera.fov=this.scope?18:50;this.camera.updateProjectionMatrix();document.body.classList.toggle('scoped',this.scope);}if(k==='x'){const enemies=this.entities.filter(e=>e.team===1&&e.hp>0&&this.isVisible(e));const current=enemies.indexOf(this.target);if(enemies.length)this.lockTarget(enemies[(current+1)%enemies.length]);}if(k==='z')this.track=!this.track;if(k==='m'){this.mapOpen=!this.mapOpen;$('.minimap-wrap').classList.toggle('expanded',this.mapOpen);}if(k==='tab'){this.scoreOpen=true;$('#scoreboard').hidden=false;this.renderScoreboard();}if(k==='p'){this.secondaryOff=!this.secondaryOff;this.message(this.secondaryOff?'副炮已停火':'副炮自由开火');}}
 selectAmmo(ammo){if(ammo==='TORP'&&!this.player.spec.torps){this.message('本舰未装备鱼雷。');return;}this.ammo=ammo;this.message(ammo==='TORP'?'鱼雷发射管准备 · 再按 3 切换宽 / 窄扇面':`${ammo==='AP'?'穿甲弹':'高爆弹'}已选用 · 下一次发射使用`);this.updateHUD();}
 lockTarget(e){if(!e||e.hp<=0||e.team===0)return;this.target=e;this.message('锁定目标：'+e.spec.name);}
 isVisible(e,team=0){if(e.team===team)return true;const range=e.spec.torps?1450:2900;const boosted=team===0&&this.consumables.boost.active>0&&this.selected!=='shimakaze';const observers=this.entities.filter(a=>a.team===team&&a.hp>0);const nearby=observers.some(a=>a.team===team&&a.hp>0&&distance(a,e)<(boosted?range*1.3:range)&&!this.blocked(a,e));const smoked=this.smokes.some(s=>distance(s,e)<s.radius);return nearby&&(!smoked||e.detected>0||(boosted&&this.selected==='bismarck'&&distance(this.player,e)<950)||observers.some(a=>distance(a,e)<260));}
 blocked(a,b){return this.islands.some(i=>segmentCircle(a,b,i,i.r));}
 useConsumable(id){const c=this.consumables[id];if(this.finished||document.querySelector('dialog[open]'))return;if(c.cool>0||c.active>0||!c.count){this.message('消耗品尚未就绪');return;}if(id==='heal'&&!this.player.spec.torps&&this.player.hp>=this.player.spec.hp){this.message('舰体状态良好，无需维修');return;}c.active=c.duration;c.count--;if(id==='repair'){this.player.fire=0;this.player.flood=0;this.player.disabled=0;this.player.immune=c.duration;}this.message(c.name+'已启动');audio.sound('click');}
 fire(e,salvo=false){if(e.hp<=0||this.finished||document.querySelector('dialog[open]'))return;if(e.player&&this.ammo==='TORP'){this.fireTorpedoes(e);return;}const dest=e.player?this.aim.clone():this.predict(e,e.target);if(!dest)return;const dist=Math.hypot(dest.x-e.x,dest.z-e.z),range=e.spec.range*(e.player&&this.consumables.boost.active>0&&this.selected!=='bismarck'?1.2:1);if(dist>range){if(e.player)this.message('目标超出主炮射程');return;}const turrets=e.mesh.userData.turrets;let fired=0;for(let i=0;i<turrets.length;i++){if(e.turretCool[i]>0)continue;const desired=Math.atan2(dest.x-e.x,dest.z-e.z)-e.heading;if(Math.abs(angleDiff(desired,turrets[i].rotation.y))>.23)continue;const rear=turrets[i].position.z<0;const rel=Math.abs(angleDiff(desired,0));if((rear&&rel<.44)||(!rear&&rel>2.76))continue;const origin=turrets[i].getWorldPosition(V());const rotation=e.heading+turrets[i].rotation.y;origin.add(V(Math.sin(rotation)*17,3,Math.cos(rotation)*17));e.turretCool[i]=e.spec.reload;const n=e.id==='bismarck'||e.spec.torps?2:3;for(let j=0;j<n;j++){const scatter=(e.player?1:this.difficulty==='hard'?.65:this.difficulty==='easy'?2.2:1.1)*(4+dist*.012);const point=dest.clone().add(V((Math.random()-.5)*scatter,0,(Math.random()-.5)*scatter));this.makeShell(origin,point,e,e.player?this.ammo:(e.spec.torps||Math.random()<.18?'HE':'AP'));}this.effects.emit(origin,'fire',7,1.2);this.effects.emit(origin,'smoke',4,1.3);fired++;if(!salvo)break;}if(fired){e.detected=18;if(e.player){this.shots+=fired*(e.id==='bismarck'||e.spec.torps?2:3);this.shake=.6;audio.sound('gun');}else if(distance(e,this.player)<1500)audio.sound('gun',.2);}else if(e.player&&salvo)this.message('等待炮塔转向或装填完成');}
 predict(e,target,torpedo=false){if(!target||target.hp<=0)return null;const dist=distance(e,target),flight=dist/(torpedo?e.spec.torpedo.speed:210);return V(target.x+Math.sin(target.heading)*target.speed*flight,4,target.z+Math.cos(target.heading)*target.speed*flight);}
 makeShell(from,to,owner,ammo){const flight=Math.max(.8,Math.hypot(to.x-from.x,to.z-from.z)/210),h=Math.min(190,flight*22);const mesh=new T.Mesh(new T.SphereGeometry(.8,6,4),new T.MeshBasicMaterial({color:ammo==='HE'?0xffb362:0xfff7d0}));mesh.scale.set(1,1,3.5);mesh.position.copy(from);this.group.add(mesh);const lineGeo=new T.BufferGeometry().setFromPoints([from,from]);const line=new T.Line(lineGeo,new T.LineBasicMaterial({color:ammo==='HE'?0xfbb985:0xf9eed1,transparent:true,opacity:.65}));this.group.add(line);this.shells.push({from:from.clone(),to,owner,ammo,flight,h,t:0,mesh,line,prev:from.clone()});}
 fireTorpedoes(e){
   if(e.torpCool>0){if(e.player)this.message(`鱼雷装填中 · ${Math.ceil(e.torpCool)} 秒`);return;}
   const dest=e.player?this.aim:this.predict(e,e.target,true);if(!dest)return;
   const spec=e.spec.torpedo,range=Math.hypot(dest.x-e.x,dest.z-e.z);
   if(range>spec.range||range<spec.armingDistance){if(e.player)this.message(`鱼雷有效距离 ${(spec.armingDistance/100).toFixed(1)}–${spec.range/100} km`);return;}
   const base=Math.atan2(dest.x-e.x,dest.z-e.z),n=e.player?5:3,spread=e.player?(this.torpWide?.075:.028):.045;
   for(let i=0;i<n;i++){const heading=base+(i-(n-1)/2)*spread;const mesh=new T.Mesh(new T.CylinderGeometry(.6,.6,7,6),new T.MeshStandardMaterial({color:0x313b40,roughness:.4}));mesh.rotation.x=Math.PI/2;const group=new T.Group();group.add(mesh);group.position.set(e.x+Math.sin(heading)*25,.2,e.z+Math.cos(heading)*25);group.rotation.y=heading;this.group.add(group);this.torpedoes.push({mesh:group,owner:e,heading,travelled:0,spec,wake:0});}
   if(e.player){const bank=e.torpBanks.findIndex(v=>v<=0);e.torpBanks[bank]=spec.reload;e.torpCool=Math.min(...e.torpBanks);}else e.torpCool=spec.reload;
   if(e.player){this.message(`鱼雷已发射 · ${n} 枚 ${this.torpWide?'宽':'窄'}扇面`);audio.sound('splash');}
 }
 damageShip(target,amount,owner,kind='装甲穿透',fire=false){if(target.hp<=0)return;const damage=Math.min(target.hp,Math.round(amount*(target.player?(this.difficulty==='easy'?.35:this.difficulty==='hard'?1.12:.65):1)));target.hp-=damage;target.repairable+=damage*(kind==='核心区命中'?.1:kind==='火灾'||kind==='进水'?1:.5);if(fire&&target.immune<=0){target.fire=Math.min(60,target.fire+25);target.fireOwner=owner;}if(owner?.player){this.damage+=damage;if(!['副炮命中','火灾','进水'].includes(kind)){this.hits++;this.hitNotice=kind+(damage?'  + '+damage.toLocaleString():'');this.hitUntil=this.time+2.8;audio.sound('hit',.55);}}if(target.player){this.shake=.32;document.body.classList.add('hit-flash');clearTimeout(this.flashTimer);this.flashTimer=setTimeout(()=>document.body.classList.remove('hit-flash'),240);}for(const c of this.caps)if(distance(target,c)<210&&c.owner!==target.team)c.progress*=.5;if(target.hp<=0){target.hp=0;target.dead=.01;this.score[owner?owner.team:1-target.team]+=70;this.score[target.team]=Math.max(0,this.score[target.team]-45);this.effects.emit(V(target.x,7,target.z),'fire',30,5);this.effects.emit(V(target.x,12,target.z),'smoke',20,5);if(owner?.player)this.kills++;this.feed(`${owner?.spec.name||'战斗损伤'} 击沉 ${target.spec.name}`,owner?.team===0);if(target.player){this.end(false,'你的战舰已被击沉');}else if(this.target===target){this.target=null;this.key('x');}}}
 updateProjectiles(dt){for(let i=this.shells.length-1;i>=0;i--){const s=this.shells[i];s.t+=dt;const t=clamp(s.t/s.flight,0,1);s.prev.copy(s.mesh.position);s.mesh.position.lerpVectors(s.from,s.to,t);s.mesh.position.y+=Math.sin(t*Math.PI)*s.h;s.mesh.lookAt(s.mesh.position.clone().add(s.mesh.position.clone().sub(s.prev)));s.line.geometry.setFromPoints([s.mesh.position,s.prev.clone().lerp(s.from,.04)]);let hit=false;if(s.mesh.position.y<25){for(const e of this.entities){if(e.hp<=0||e===s.owner||e.team===s.owner.team)continue;const impact=hitShip(s.mesh.position,e,4);if(impact.hit){const result=armorHit(s.owner,e,s.ammo,impact);this.damageShip(e,result.damage,s.owner,result.kind,result.fire);this.effects.emit(s.mesh.position,'fire',9,1.6);this.effects.emit(s.mesh.position,'smoke',5,1.2);hit=true;break;}}}if(!hit&&this.islands.some(a=>distance(a,{x:s.mesh.position.x,z:s.mesh.position.z})<a.r&&s.mesh.position.y<a.height)){this.effects.emit(s.mesh.position,'smoke',4,1.8);hit=true;}if(t>=1&&!hit){this.effects.emit(s.mesh.position,'splash',8,1.4);if(s.owner.player)audio.sound('splash',.18);hit=true;}if(hit){this.group.remove(s.mesh,s.line);s.mesh.geometry.dispose();s.mesh.material.dispose();s.line.geometry.dispose();s.line.material.dispose();this.shells.splice(i,1);}if(this.finished)return;}
 for(let i=this.torpedoes.length-1;i>=0;i--){
   const t=this.torpedoes[i],step=Math.min(t.spec.speed*dt,t.spec.range-t.travelled);t.travelled+=step;
   t.mesh.position.x+=Math.sin(t.heading)*step;t.mesh.position.z+=Math.cos(t.heading)*step;t.wake+=dt;
   if(t.wake>.13){t.wake=0;this.effects.emit(t.mesh.position,'wake',1,.7);}
   let hit=false;for(const e of this.entities){if(e.hp<=0||e.team===t.owner.team)continue;if(hitShip(t.mesh.position,e,5).hit){
     if(t.travelled>=t.spec.armingDistance){this.damageShip(e,t.spec.damage,t.owner,'鱼雷命中');if(e.immune<=0){e.flood=30;e.floodOwner=t.owner;}this.effects.emit(t.mesh.position,'splash',20,3);this.effects.emit(t.mesh.position,'fire',10,2);}
     hit=true;break;
   }}
   if(hit||t.travelled>=t.spec.range||this.islands.some(a=>distance(a,{x:t.mesh.position.x,z:t.mesh.position.z})<a.r)){this.group.remove(t.mesh);t.mesh.traverse(o=>{if(o.isMesh){o.geometry.dispose();o.material.dispose();}});this.torpedoes.splice(i,1);}if(this.finished)return;
 }}

 ai(e,dt){
   const enemies=this.entities.filter(t=>t.team!==e.team&&t.hp>0&&this.isVisible(t,e.team));
   e.target=enemies.sort((a,b)=>distance(e,a)-distance(e,b))[0];
   const assigned=this.caps[e.lane],cap=assigned.owner!==e.team?assigned:this.caps.filter(c=>c.owner!==e.team).sort((a,b)=>distance(e,a)-distance(e,b))[0]||assigned;
   const course=navigate(e,battleCourse(e,e.target,cap),this.islands);
   e.rudder=clamp(angleDiff(course.heading,e.heading)*1.8,-1,1);
   e.goalSpeed=e.spec.knots*SPEED_PER_KNOT*course.throttle;
   if(!e.target)return;
   const d=distance(e,e.target);e.cool-=dt;
   if(e.cool<=0&&d<e.spec.range&&!this.blocked(e,e.target)){this.fire(e,true);e.cool=.6;}
   if(e.spec.torps&&d<e.spec.torpedo.range&&d>e.spec.torpedo.armingDistance&&e.torpCool<=0&&!this.blocked(e,e.target))this.fireTorpedoes(e);
   if(e.hp<e.spec.hp*.45&&e.heal<=0&&e.repairable>1000&&Math.random()<dt*.03)e.heal=18;
 }
 updateShip(e,dt,t){if(e.hp<=0){e.dead+=dt;e.mesh.position.y=-Math.min(25,e.dead*1.4);e.mesh.rotation.z=Math.min(.5,e.dead*.035);if(e.dead>18)e.mesh.visible=false;return;}e.turretCool=e.turretCool.map(c=>Math.max(0,c-dt));if(e.player&&e.spec.torps){e.torpBanks=e.torpBanks.map(v=>Math.max(0,v-dt));e.torpCool=Math.min(...e.torpBanks);}else e.torpCool=Math.max(0,e.torpCool-dt);e.detected=Math.max(0,e.detected-dt);e.immune=Math.max(0,e.immune-dt);e.disabled=Math.max(0,e.disabled-dt);if(e.player){const steering=this.keys.has('a')||this.keys.has('d');const rud=steering?(Number(this.keys.has('a'))-Number(this.keys.has('d'))):this.lockRudder;e.rudder+=(rud-e.rudder)*Math.min(1,dt*1.7);const boost=this.selected==='shimakaze'&&this.consumables.boost.active>0?1.22:1;e.goalSpeed=[-.24,0,.25,.5,.75,1][this.throttle]*e.spec.knots*SPEED_PER_KNOT*boost*(e.flood>0?.7:1);}else this.ai(e,dt);e.speed+=(e.goalSpeed-e.speed)*Math.min(1,dt*.09);e.heading+=e.rudder*e.spec.turn*dt*Math.min(1,Math.abs(e.speed)/(e.spec.knots*SPEED_PER_KNOT*.7))*(e.speed<0?-1:1);const old={x:e.x,z:e.z,heading:e.mesh.rotation.y};e.x+=Math.sin(e.heading)*e.speed*dt;e.z+=Math.cos(e.heading)*e.speed*dt;if(hullTouchesLand(e,this.islands)){e.x=old.x;e.z=old.z;e.heading=old.heading;e.speed*=.25;if(e.player&&this.time-this.statusTimer>3){this.message('浅滩警报 · 倒车并转舵脱离');this.statusTimer=this.time;}}
 const boundary=MAP_HALF_SIZE-e.mesh.userData.L*.5;if(Math.abs(e.x)>boundary||Math.abs(e.z)>boundary){e.x=clamp(e.x,-boundary,boundary);e.z=clamp(e.z,-boundary,boundary);e.speed*=.95;if(e.player&&this.time-this.statusTimer>4){this.message('已抵达战区边界，请转向');this.statusTimer=this.time;}}
 e.mesh.position.set(e.x,Math.sin(t*.7+e.aiPhase)*.25,e.z);e.mesh.rotation.y=e.heading;e.mesh.rotation.z=Math.sin(t*.55+e.aiPhase)*.008+e.rudder*e.speed*.0012;
 const aim=e.player?this.aim:this.predict(e,e.target);if(aim){const desired=Math.atan2(aim.x-e.x,aim.z-e.z)-e.heading;e.mesh.userData.turrets.forEach((turret,i)=>{const d=angleDiff(desired,turret.rotation.y);turret.rotation.y+=clamp(d,-dt*(e.spec.torps?.7:.36),dt*(e.spec.torps?.7:.36));});}
 e.wake+=dt;if(e.wake>.22){e.wake=0;if(Math.abs(e.speed)>1){const stern=V(e.x-Math.sin(e.heading)*e.mesh.userData.L*.48,.2,e.z-Math.cos(e.heading)*e.mesh.userData.L*.48);this.effects.emit(stern,'wake',2,Math.abs(e.speed)/14);const bow=V(e.x+Math.sin(e.heading)*e.mesh.userData.L*.47,.2,e.z+Math.cos(e.heading)*e.mesh.userData.L*.47);this.effects.emit(bow,'wake',1,Math.abs(e.speed)/25);}if(e.fire>0){this.effects.emit(V(e.x,10,e.z),'fire',2,2);this.effects.emit(V(e.x,17,e.z),'smoke',1,2.5);}else if(Math.random()<.2)this.effects.emit(V(e.x,18,e.z),'smoke',1,.6);}
 if(e.fire>0){e.fire-=dt;this.damageShip(e,e.spec.hp*.002*dt,e.fireOwner||null,'火灾');if(e.hp<=0)return;}if(e.flood>0){e.flood-=dt;this.damageShip(e,e.spec.hp*.003*dt,e.floodOwner||null,'进水');if(e.hp<=0)return;}if(e.heal>0){e.heal-=dt;const amount=Math.min(e.spec.hp*.005*dt,e.repairable,e.spec.hp-e.hp);e.hp+=amount;e.repairable-=amount;}
 e.secCool-=dt;if(e.secCool<=0&&!e.spec.torps&&!(e.player&&this.secondaryOff)){const enemy=this.entities.find(a=>a.team!==e.team&&a.hp>0&&this.isVisible(a,e.team)&&distance(e,a)<(e.id==='bismarck'?660:420)&&!this.blocked(e,a));if(enemy){const from=V(e.x,8,e.z),to=V(enemy.x+(Math.random()-.5)*20,8,enemy.z);this.damageShip(enemy,e.id==='bismarck'?450:220,e,'副炮命中',Math.random()<.035);this.effects.emit(to,'fire',3,.7);e.secCool=e.id==='bismarck'?1.8:3;}}}
 update(dt,t){this.updateCamera(dt);if(document.querySelector('dialog[open]')||this.finished||(this.mouseInput&&!this.mouseControls.isLocked)){this.keys.clear();this.fireHeld=false;return;}this.time+=dt;this.seconds-=dt;this.shake=Math.max(0,this.shake-dt*2);this.computeAim();if(this.fireHeld&&this.time-this.lastFire>.35){this.fire(this.player,false);this.lastFire=this.time;}for(const e of this.entities){this.updateShip(e,dt,t);if(this.finished)return;}for(let i=0;i<this.entities.length;i++)for(let j=i+1;j<this.entities.length;j++){const a=this.entities[i],b=this.entities[j],d=distance(a,b),r=(a.mesh.userData.W+b.mesh.userData.W)*.7;if(a.hp>0&&b.hp>0&&d<r){const angle=Math.atan2(a.x-b.x,a.z-b.z);a.x+=Math.sin(angle)*(r-d)*.5;a.z+=Math.cos(angle)*(r-d)*.5;b.x-=Math.sin(angle)*(r-d)*.5;b.z-=Math.cos(angle)*(r-d)*.5;a.speed*=.96;b.speed*=.96;if(a.team!==b.team){this.damageShip(a,1200*dt,b,'撞击');this.damageShip(b,1200*dt,a,'撞击');}}}
 if(this.finished)return;for(const [id,c] of Object.entries(this.consumables)){if(c.active>0){c.active-=dt;if(id==='heal'){if(this.selected==='shimakaze'){if(Math.floor(this.time*2)!==Math.floor((this.time-dt)*2))this.addSmoke();}else{const n=Math.min(this.player.spec.hp*.006*dt,this.player.repairable,this.player.spec.hp-this.player.hp);this.player.hp+=n;this.player.repairable-=n;}}if(c.active<=0)c.cool=c.cooldown;}else c.cool=Math.max(0,c.cool-dt);}for(let i=this.smokes.length-1;i>=0;i--){const s=this.smokes[i];s.life-=dt;s.mesh.material.opacity=Math.min(.18,s.life*.006);if(s.life<=0){this.group.remove(s.mesh);s.mesh.geometry.dispose();s.mesh.material.dispose();this.smokes.splice(i,1);}}
 for(const c of this.caps){const prev=c.owner;captureStep(c,this.entities,dt);if(prev!==c.owner){this.feed(`${c.owner===0?'我方':'敌方'} 占领 ${c.name} 区`,c.owner===0);if(c.owner===0)this.message(`${c.name} 区已占领，持续获得制海积分`);}if(c.owner>=0&&!this.entities.some(e=>e.hp>0&&e.team!==c.owner&&distance(e,c)<210))this.score[c.owner]+=dt*1.3;c.mesh.material.color.set(c.contested?0xf0ca80:c.owner===0?0x65c6d2:c.owner===1?0xec7b70:0xd8cfad);}
 this.updateProjectiles(dt);if(this.finished)return;this.effects.update(dt);this.updateLabels();this.drawMap();this.uiTime+=dt;if(this.uiTime>.1){this.uiTime=0;this.updateHUD();}if(this.score[0]>=1000||!this.entities.some(e=>e.team===1&&e.hp>0))this.end(true,'你们夺取了这片海域的制海权');else if(this.score[1]>=1000||!this.entities.some(e=>e.team===0&&e.hp>0))this.end(false,'敌方控制了这片海域');else if(this.seconds<=0)this.end(this.score[0]>=this.score[1],'战斗时间结束，按舰队积分结算');}
 addSmoke(){const p=this.player;const mesh=new T.Mesh(new T.SphereGeometry(75,12,7),new T.MeshBasicMaterial({color:0xb6bfc1,transparent:true,opacity:.18,depthWrite:false}));mesh.scale.y=.32;mesh.position.set(p.x,10,p.z);this.group.add(mesh);this.smokes.push({x:p.x,z:p.z,radius:90,life:35,mesh});}
 computeAim(){const range=this.ammo==='TORP'?this.player.spec.torpedo.range:this.player.spec.range;const ray=new T.Raycaster();ray.setFromCamera(this.pointer,this.camera);const point=V();const intersect=ray.ray.intersectPlane(new T.Plane(V(0,1,0),-4),point);if(intersect&&point.distanceTo(this.player.mesh.position)<range*1.35)this.aim.copy(point);else this.aim.set(this.player.x+Math.sin(this.viewYaw)*range,4,this.player.z+Math.cos(this.viewYaw)*range);}
 cameraDestination(){const p=this.player,behind=this.scope?-(p.mesh.userData.L*.65+12):this.zoom;return V(p.x-Math.sin(this.viewYaw)*behind,this.scope?25:65+this.zoom*.16,p.z-Math.cos(this.viewYaw)*behind);}
 updateCamera(dt){
   const p=this.player,direction=V();this.lookCamera.getWorldDirection(direction);this.viewYaw=Math.atan2(direction.x,direction.z);
   this.mouseControls.pointerSpeed=1.5*this.camera.fov/50;
   const shell=this.track?this.shells.find(s=>s.owner.player):null;
   p.mesh.visible=p.hp>0&&!this.scope&&!shell;
   if(this.target&&!this.isVisible(this.target))this.target=null;
   const dest=this.cameraDestination();if(shell)dest.copy(shell.mesh.position).add(V(-25,12,-25));
   this.camera.position.lerp(dest,Math.min(1,dt*6));
   if(this.shake){this.camera.position.x+=(Math.random()-.5)*this.shake*2;this.camera.position.y+=(Math.random()-.5)*this.shake;}
   if(shell)this.camera.lookAt(shell.mesh.position);else this.camera.quaternion.copy(this.lookCamera.quaternion);
   this.camera.updateProjectionMatrix();this.camera.updateMatrixWorld();
 }
 project(pos){const p=pos.clone().project(this.camera);return{x:(p.x+1)*innerWidth/2,y:(1-p.y)*innerHeight/2,visible:p.z>0&&p.z<1&&Math.abs(p.x)<1.15&&Math.abs(p.y)<1.15};}
 updateLabels(){for(const [e,el] of this.labels){const visible=e.hp>0&&this.isVisible(e);const pos=this.project(V(e.x,35,e.z));el.hidden=!visible||!pos.visible;if(el.hidden)continue;el.style.transform=`translate(${pos.x}px,${pos.y}px) translate(-50%,-100%)`;el.classList.toggle('locked',this.target===e);el.querySelector('i').style.width=e.hp/e.spec.hp*100+'%';el.querySelector('em').textContent=(distance(this.player,e)/100).toFixed(1)+' km';}const r=$('#reticle');r.style.left=(this.pointer.x+1)*50+'%';r.style.top=(1-this.pointer.y)*50+'%';const target=this.target;const marker=$('#lead-marker');if(target&&target.hp>0&&this.isVisible(target)&&$('#aim-assist').checked){const point=this.predict(this.player,target,this.ammo==='TORP');const p=this.project(point);marker.hidden=!p.visible;marker.style.left=p.x+'px';marker.style.top=p.y+'px';}else marker.hidden=true;}
 updateHUD(){const p=this.player;$('#hp-bar').style.width=(p.hp/p.spec.hp*100)+'%';$('#heal-bar').style.width=(Math.min(p.repairable,p.spec.hp-p.hp)/p.spec.hp*100)+'%';$('#heal-bar').style.left=(p.hp/p.spec.hp*100)+'%';$('#hp-text').textContent=`${Math.round(p.hp).toLocaleString()} / ${p.spec.hp.toLocaleString()}`;$('#speed-read').textContent=(Math.abs(p.speed)/SPEED_PER_KNOT).toFixed(1);$('#throttle-read').textContent=throttleNames[this.throttle];$('#throttle-bars').innerHTML=Array.from({length:5},(_,i)=>`<i class="${i<this.throttle?'on':''}"></i>`).join('');$('#rudder-needle').style.left=(.5-p.rudder*.45)*100+'%';$('#damage-count').textContent=Math.round(this.damage).toLocaleString();$('#hit-count').textContent=`命中 ${this.hits} · 击沉 ${this.kills}`;$('#blue-score').textContent=Math.floor(this.score[0]);$('#red-score').textContent=Math.floor(this.score[1]);$('#battle-timer').textContent=`${String(Math.floor(this.seconds/60)).padStart(2,'0')}:${String(Math.floor(this.seconds%60)).padStart(2,'0')}`;$('#team-icons').innerHTML=[0,1].map(t=>`<div class="team-${t}">${this.entities.filter(e=>e.team===t).map(e=>`<span style="opacity:${e.hp>0?1:.2}">${e.spec.torps?'◆':'▰'}</span>`).join('')}</div>`).join('<i>VS</i>');for(const c of this.caps){const el=$('#cap-'+c.name);el.className=c.contested?'contested':c.owner===0?'blue':c.owner===1?'red':'';el.title=c.contested?'正在争夺':c.owner<0?'占领中 '+Math.round(Math.abs(c.progress)*100)+'%':c.owner===0?'我方控制':'敌方控制';el.style.background=`linear-gradient(to top,${c.progress>0?'#78bfce55':'#ef8a7955'} ${Math.abs(c.progress)*100}%,transparent 0%)`;}
 $('#aim-range').textContent=(distance(p,{x:this.aim.x,z:this.aim.z})/100).toFixed(1)+' km · '+(distance(p,{x:this.aim.x,z:this.aim.z})/(this.ammo==='TORP'?p.spec.torpedo.speed:210)).toFixed(1)+' s';const ready=p.turretCool.filter(c=>c<=0).length;$('#reticle').classList.toggle('ready',ready>0);$('#turret-status').innerHTML=this.ammo==='TORP'?`<span>鱼雷 ${p.torpBanks.filter(v=>v<=0).length} / 3 组</span><b>${p.torpCool>0?Math.ceil(p.torpCool)+' s':'准备就绪'}</b><span>${this.torpWide?'宽':'窄'}扇面</span>`:p.turretCool.map((c,i)=>`<span class="turret ${c<=0?'ready':''}"><i>${['I','II','III','IV'][i]}</i><b>${c>0?c.toFixed(1)+' s':'就绪'}</b><em style="width:${(1-c/p.spec.reload)*100}%"></em></span>`).join('');document.querySelectorAll('[data-ammo]').forEach(b=>b.classList.toggle('active',b.dataset.ammo===this.ammo));for(const [id,c] of Object.entries(this.consumables)){const el=this.consumableEls[id];el.classList.toggle('active',c.active>0);el.classList.toggle('cooldown',c.cool>0||!c.count);el.querySelector('em').textContent=c.active>0?Math.ceil(c.active)+'s':c.cool>0?Math.ceil(c.cool)+'s':c.count===Infinity?'∞':c.count;}
 const detected=this.isVisible(p,1);const incoming=this.torpedoes.some(t=>t.owner.team===1&&distance(p,{x:t.mesh.position.x,z:t.mesh.position.z})<t.spec.warningRange);$('#threat-status').innerHTML=(incoming?'<strong>△ 鱼雷接近</strong>':'')+(detected?'<span>◉ 已被发现</span>':'<span class="concealed">隐蔽航行</span>');$('#ship-status').innerHTML=(p.fire>0?`<span>起火 ${Math.ceil(p.fire)}s</span>`:'')+(p.flood>0?`<span>进水 ${Math.ceil(p.flood)}s</span>`:'')+(p.immune>0?'<span class="safe">损管生效</span>':'');$('#hit-notice').textContent=this.time<this.hitUntil?this.hitNotice:'';const heading=((p.heading*180/Math.PI)%360+360)%360;$('#compass').innerHTML=`<span>W</span><i>···</i><strong>${Math.round(heading).toString().padStart(3,'0')}°</strong><i>···</i><span>E</span>`;if(this.target&&this.target.hp>0&&this.isVisible(this.target)){const target=this.target;$('#target-panel').innerHTML=`<span>锁定目标</span><strong>${target.spec.name}</strong><small>${Math.round(target.hp).toLocaleString()} HP</small>`;}else $('#target-panel').innerHTML='<span>X 切换目标 · 鼠标环顾</span>';if(this.scoreOpen)this.renderScoreboard();}
 drawMap(){const c=this.mini,w=280,scale=w/(MAP_HALF_SIZE*2),to=(x)=>w/2+x*scale;c.clearRect(0,0,w,w);c.fillStyle='#0b1f2ad9';c.fillRect(0,0,w,w);c.strokeStyle='#7ca8bc20';c.lineWidth=1;for(let i=0;i<=10;i++){c.beginPath();c.moveTo(i*w/10,0);c.lineTo(i*w/10,w);c.moveTo(0,i*w/10);c.lineTo(w,i*w/10);c.stroke();}c.font='9px sans-serif';c.fillStyle='#71909e';for(let i=0;i<10;i++){c.fillText(String(i+1),i*28+11,10);c.fillText('ABCDEFGHIJ'[i],3,i*28+20);}c.fillStyle='#47645e';for(const a of this.islands){c.beginPath();c.ellipse(to(a.x),to(a.z),a.r*scale,a.r*scale*.8,.3,0,TAU);c.fill();}for(const cap of this.caps){c.strokeStyle=cap.owner===0?'#7cc5d0':cap.owner===1?'#e78071':'#c8bb90';c.fillStyle=c.strokeStyle;c.beginPath();c.arc(to(cap.x),to(cap.z),210*scale,0,TAU);c.stroke();c.font='12px Rajdhani';c.fillText(cap.name,to(cap.x)-4,to(cap.z)+4);}for(const e of this.entities){if(e.hp<=0||(e.team===1&&!this.isVisible(e)))continue;c.save();c.translate(to(e.x),to(e.z));c.rotate(-e.heading+Math.PI);c.fillStyle=e.player?'#f6e3b4':e.team===0?'#70c6d4':'#ef8276';c.beginPath();c.moveTo(0,-7);c.lineTo(4,5);c.lineTo(0,3);c.lineTo(-4,5);c.closePath();c.fill();c.restore();}const p=this.player;c.strokeStyle='#d8c48c50';c.beginPath();c.arc(to(p.x),to(p.z),(this.ammo==='TORP'?p.spec.torpedo.range:p.spec.range)*scale,0,TAU);c.stroke();c.save();c.translate(to(p.x),to(p.z));c.rotate(-this.viewYaw+Math.PI);c.strokeStyle='#efe4c75e';c.beginPath();c.moveTo(-45,-70);c.lineTo(0,0);c.lineTo(45,-70);c.stroke();c.restore();for(const t of this.torpedoes){c.fillStyle=t.owner.team?'#e99175':'#83d7d0';c.fillRect(to(t.mesh.position.x)-1,to(t.mesh.position.z)-1,2,2);}}
 renderScoreboard(){$('#scoreboard').innerHTML=`<h2>舰队战况</h2><div class="teams">${[0,1].map(team=>`<section><h3>${team?'敌方舰队':'我方舰队'}</h3>${this.entities.filter(e=>e.team===team).map(e=>`<div class="score-unit ${e.hp<=0?'sunk':''}"><strong>${e.spec.name}${e.player?' · 你':''}</strong><span>${e.hp<=0?'已沉没':Math.round(e.hp).toLocaleString()+' HP'}</span></div>`).join('')}</section>`).join('')}</div><p>松开 Tab 返回战斗</p>`;}
 message(msg){$('#battle-caption').textContent=msg;clearTimeout(this.messageTimer);this.messageTimer=setTimeout(()=>{const el=$('#battle-caption');if(el)el.textContent='';},6000);}
 feed(msg,ally){const el=document.createElement('div');el.textContent=msg;el.className=ally?'friendly':'hostile';$('#battle-feed').prepend(el);setTimeout(()=>el.remove(),10000);}
 end(win,reason){if(this.finished)return;this.finished=true;this.keys.clear();$('#result-title').textContent=win?'战斗胜利':'战斗结束';$('#result-title').style.color=win?'#d1b27a':'#d5e0e5';$('#result-reason').textContent=reason;$('#result-stats').innerHTML=`<div><strong>${Math.round(this.damage).toLocaleString()}</strong><span>造成伤害</span></div><div><strong>${this.kills}</strong><span>击沉舰船</span></div><div><strong>${this.hits}</strong><span>主炮 / 鱼雷命中</span></div><div><strong>${Math.floor(this.score[0])} : ${Math.floor(this.score[1])}</strong><span>舰队积分</span></div>`;this.openDialog('#result-dialog');}
 dispose(){this.finished=true;this.abort.abort();this.mouseControls.dispose();if(document.pointerLockElement===this.renderer.domElement)document.exitPointerLock();clearTimeout(this.messageTimer);clearTimeout(this.flashTimer);this.effects.dispose();this.scene.remove(this.group);this.group.traverse(o=>{if(o.isMesh||o.isLine)o.geometry?.dispose();});document.body.classList.remove('scoped','hit-flash');this.camera.fov=45;this.camera.updateProjectionMatrix();}
}
