import * as T from 'three';
export class AudioEngine{
 constructor(){this.ctx=null;this.enabled=false;this.volume=.45;}
 start(){if(!this.ctx){this.ctx=new AudioContext();this.master=this.ctx.createGain();this.master.connect(this.ctx.destination);const b=this.ctx.createBuffer(1,this.ctx.sampleRate*3,this.ctx.sampleRate),d=b.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1)*.15;const n=this.ctx.createBufferSource();n.buffer=b;n.loop=true;const f=this.ctx.createBiquadFilter();f.type='lowpass';f.frequency.value=180;const v=this.ctx.createGain();v.gain.value=.25;n.connect(f).connect(v).connect(this.master);n.start();}this.ctx.resume();this.enabled=true;this.master.gain.value=this.volume;}
 toggle(){if(!this.enabled)this.start();else{this.enabled=false;this.master.gain.value=0;}return this.enabled;}
 setVolume(v){this.volume=v;if(this.master)this.master.gain.value=this.enabled?v:0;}
 sound(type,scale=1){if(!this.enabled||!this.ctx)return;const c=this.ctx,t=c.currentTime,duration=type==='gun'?1.8:type==='hit'?1.2:type==='splash'?.7:.22;const b=c.createBuffer(1,c.sampleRate*duration,c.sampleRate),a=b.getChannelData(0);for(let i=0;i<a.length;i++)a[i]=(Math.random()*2-1)*Math.pow(1-i/a.length,3);const src=c.createBufferSource();src.buffer=b;const filter=c.createBiquadFilter();filter.type='lowpass';filter.frequency.value=type==='gun'?240:type==='hit'?420:1200;const gain=c.createGain();gain.gain.setValueAtTime(scale*(type==='gun'?.9:.38),t);gain.gain.exponentialRampToValueAtTime(.001,t+duration);src.connect(filter).connect(gain).connect(this.master);src.start();if(type==='gun'||type==='hit'){const o=c.createOscillator();o.frequency.setValueAtTime(type==='gun'?95:65,t);o.frequency.exponentialRampToValueAtTime(24,t+.6);const g=c.createGain();g.gain.setValueAtTime(.35*scale,t);g.gain.exponentialRampToValueAtTime(.001,t+.8);o.connect(g).connect(this.master);o.start();o.stop(t+.8);}}
}
export const audio=new AudioEngine();
export class Effects{
 constructor(scene){this.scene=scene;this.particles=[];this.pool=[];const canvas=document.createElement('canvas');canvas.width=canvas.height=64;const ctx=canvas.getContext('2d'),gradient=ctx.createRadialGradient(32,32,0,32,32,32);gradient.addColorStop(0,'rgba(255,255,255,1)');gradient.addColorStop(.3,'rgba(255,255,255,.65)');gradient.addColorStop(1,'rgba(255,255,255,0)');ctx.fillStyle=gradient;ctx.fillRect(0,0,64,64);this.softTexture=new T.CanvasTexture(canvas);this.geometry=new T.SphereGeometry(1,7,5);this.materials={fire:new T.SpriteMaterial({map:this.softTexture,color:0xffa542,transparent:true,depthWrite:false,blending:T.AdditiveBlending}),smoke:new T.SpriteMaterial({map:this.softTexture,color:0x4b5155,transparent:true,depthWrite:false}),splash:new T.MeshBasicMaterial({color:0xd5eff2,transparent:true}),wake:new T.MeshBasicMaterial({color:0xb0d2d8,transparent:true,depthWrite:false})};}
 emit(pos,kind='splash',count=12,size=1){for(let i=0;i<count;i++){if(this.particles.length>440){this.remove(0);}const mat=this.materials[kind].clone(),m=kind==='smoke'||kind==='fire'?new T.Sprite(mat):new T.Mesh(this.geometry,mat);m.position.copy(pos);const life=kind==='smoke'?4+Math.random()*3:kind==='wake'?3:kind==='fire'?.55+Math.random():.7+Math.random()*.8;const sc=(kind==='smoke'?3:kind==='wake'?2:.5+Math.random())*size;m.scale.setScalar(sc);if(kind==='wake')m.scale.y=.04;this.scene.add(m);this.particles.push({mesh:m,age:0,life,size:sc,kind,v:new T.Vector3((Math.random()-.5)*(kind==='splash'?12:5)*size,kind==='splash'?10+Math.random()*18:kind==='smoke'?4+Math.random()*4:kind==='wake'?0:3,(Math.random()-.5)*6*size)});}}
 remove(i){const p=this.particles[i];this.scene.remove(p.mesh);p.mesh.material.dispose();this.particles.splice(i,1);}
 update(dt){for(let i=this.particles.length-1;i>=0;i--){const p=this.particles[i];p.age+=dt;if(p.age>p.life){this.remove(i);continue;}p.mesh.position.addScaledVector(p.v,dt);if(p.kind==='splash')p.v.y-=22*dt;const q=1-p.age/p.life;p.mesh.material.opacity=q*(p.kind==='smoke'?.55:p.kind==='wake'?.26:1);if(p.kind==='smoke')p.mesh.scale.setScalar(p.size*(1+p.age*.75));if(p.kind==='wake')p.mesh.scale.set(p.size*(1+p.age),.05,p.size*(2+p.age));}}
 dispose(){while(this.particles.length)this.remove(0);this.geometry.dispose();this.softTexture.dispose();Object.values(this.materials).forEach(m=>m.dispose());}
}
