import * as T from 'three';
import {Water} from 'three/addons/objects/Water.js';
import {Sky} from 'three/addons/objects/Sky.js';
import {SHIPS,buildShip} from './ships.js';
import {audio} from './effects.js';
import {Battle} from './battle.js';
import waterNormalsUrl from '../assets/waternormals.jpg';
const $=s=>document.querySelector(s);
const renderer=new T.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;$('#scene').appendChild(renderer.domElement);
const scene=new T.Scene();scene.fog=new T.FogExp2(0x81939c,.00016);const camera=new T.PerspectiveCamera(45,innerWidth/innerHeight,.4,25000);
const sky=new Sky();sky.scale.setScalar(18000);scene.add(sky);const sun=new T.Vector3().setFromSphericalCoords(1,T.MathUtils.degToRad(79),T.MathUtils.degToRad(125));sky.material.uniforms.sunPosition.value.copy(sun);sky.material.uniforms.turbidity.value=7;sky.material.uniforms.rayleigh.value=1.4;sky.material.uniforms.mieCoefficient.value=.008;sky.material.uniforms.mieDirectionalG.value=.85;
scene.add(new T.HemisphereLight(0xc5dfed,0x253139,2.4));const light=new T.DirectionalLight(0xffdfb0,3.6);light.position.copy(sun).multiplyScalar(500);scene.add(light);
const normals=new T.TextureLoader().load(waterNormalsUrl,t=>{t.wrapS=t.wrapT=T.RepeatWrapping;});const water=new Water(new T.PlaneGeometry(30000,30000),{textureWidth:512,textureHeight:512,waterNormals:normals,sunDirection:sun,sunColor:0xffe6c8,waterColor:0x173c49,distortionScale:3.1,fog:true});water.rotation.x=-Math.PI/2;scene.add(water);
const islandSpecs=[[-820,-750,220,150],[-570,260,155,90],[650,-340,180,130],[1040,820,260,190],[-1450,1100,300,210],[250,-1500,270,160],[1800,-1200,280,160],[-1600,-1900,340,220]];
const islands=[];for(const [x,z,r,h] of islandSpecs){const geo=new T.SphereGeometry(1,28,16,0,Math.PI*2,0,Math.PI/2);const p=geo.attributes.position;for(let i=0;i<p.count;i++){const a=p.getX(i),b=p.getY(i),c=p.getZ(i);const n=1+.16*Math.sin(a*12+c*8)+.1*Math.cos(c*18-b*6);p.setXYZ(i,a*r*n,b*h*(.7+.3*Math.sin(a*7+c*5)),c*r*n);}geo.computeVertexNormals();const m=new T.Mesh(geo,new T.MeshStandardMaterial({color:0x48594f,roughness:1,flatShading:true}));m.position.set(x,-3,z);scene.add(m);islands.push({x,z,r:r*.9,mesh:m});const shore=new T.Mesh(new T.CircleGeometry(r*1.05,40),new T.MeshBasicMaterial({color:0x54918d,transparent:true,opacity:.2}));shore.rotation.x=-Math.PI/2;shore.position.set(x,.1,z);scene.add(shore);}
let selected='yamato',portShip=buildShip(selected),orbit=-.82,zoom=innerWidth<760?250:195,drag=false,lastX=0,time=0;scene.add(portShip);portShip.position.set(0,0,0);
function selectShip(id){selected=id;scene.remove(portShip);portShip=buildShip(id);scene.add(portShip);const s=SHIPS[id];$('#ship-title').textContent=s.name;$('.ship-en').textContent=s.en;$('.ship-tier').innerHTML=`${s.tier} <span>${s.type}</span>`;$('.ship-intro .eyebrow').innerHTML=`${s.nation}海军 <span>·</span> ${s.year}`;$('#ship-desc').textContent=s.description;$('#gun-value').innerHTML=s.guns.replace(' mm',' <small>mm</small>');$('#speed-value').innerHTML=s.knots+' <small>kn</small>';$('#hp-value').textContent=s.hp.toLocaleString();$('.ship-note span').textContent='0'+(Object.keys(SHIPS).indexOf(id)+1)+' — 04';document.querySelectorAll('.ship-card').forEach(b=>b.classList.toggle('selected',b.dataset.ship===id));}
$('#ship-cards').innerHTML=Object.entries(SHIPS).map(([id,s])=>`<button class="ship-card ${id===selected?'selected':''}" data-ship="${id}"><span class="tier">${s.tier} <span>／ ${s.type}</span></span><strong>${s.name}</strong><span class="card-en">${s.en}</span><span class="card-country">${s.nation} · ${s.year}</span><span class="card-guns">${s.guns}</span></button>`).join('');document.querySelectorAll('[data-ship]').forEach(b=>b.onclick=()=>selectShip(b.dataset.ship));
const ctx=$('#port-map').getContext('2d');ctx.fillStyle='#56727755';for(const [x,z,r] of islandSpecs){ctx.beginPath();ctx.ellipse(150+x/14,70+z/28,r/17,r/25,.5,0,7);ctx.fill();}
let game=null;const clock=new T.Clock();function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.05);time+=dt;water.material.uniforms.time.value+=dt*.6;if(game){game.update(dt,time);}else{orbit+=drag?0:dt*.006;portShip.rotation.z=Math.sin(time*.55)*.007;portShip.position.y=Math.sin(time*.7)*.25;const target=new T.Vector3(Math.cos(orbit)*zoom,zoom*.37,Math.sin(orbit)*zoom);camera.position.lerp(target,.07);camera.lookAt(innerWidth<760?0:12,3,0);}renderer.render(scene,camera);}animate();
renderer.domElement.addEventListener('pointerdown',e=>{if(!game){drag=true;lastX=e.clientX;renderer.domElement.setPointerCapture(e.pointerId);}});renderer.domElement.addEventListener('pointermove',e=>{if(!game&&drag){orbit+=(e.clientX-lastX)*.008;lastX=e.clientX;}});renderer.domElement.addEventListener('pointerup',()=>drag=false);renderer.domElement.addEventListener('wheel',e=>{e.preventDefault();if(!game)zoom=T.MathUtils.clamp(zoom+e.deltaY*.12,120,330);},{passive:false});
window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>{b.closest('dialog').close();if(game)game.startMouseLook();});$('#guide-btn').onclick=()=>game?game.openDialog('#guide-dialog'):$('#guide-dialog').showModal();$('#settings-btn').onclick=()=>game?game.openDialog('#settings-dialog'):$('#settings-dialog').showModal();$('#port-nav').onclick=()=>game&&!game.finished?game.openDialog('#pause-dialog'):null;
$('#sound-btn').onclick=()=>{const enabled=audio.toggle();$('#sound-btn').textContent=enabled?'♫':'♪';$('#sound-btn').setAttribute('aria-label',enabled?'关闭声音':'开启声音');};$('#volume').oninput=e=>audio.setVolume(e.target.value/100);$('#quality').onchange=e=>{renderer.setPixelRatio(e.target.value==='high'?Math.min(devicePixelRatio,1.6):1);};
$('#guide-content').innerHTML=`<div class="guide-tabs"><span>01 航行与火控</span><span>02 制海权</span></div><div class="key-grid"><div><kbd>W S / ↑ ↓</kbd><span>增加 / 降低车钟档位；最低档为倒车</span></div><div><kbd>A D / ← →</kbd><span>按住向左 / 向右转舵，松开回中</span></div><div><kbd>Q / E</kbd><span>逐档锁定左 / 右舵位</span></div><div><kbd>鼠标</kbd><span>直接环顾与瞄准，无需按住鼠标；准星固定中央</span></div><div><kbd>左键</kbd><span>单击单塔，双击齐射，长按轮射</span></div><div><kbd>Shift</kbd><span>切换望远镜；滚轮缩放</span></div><div><kbd>1 / 2</kbd><span>选择高爆 / 穿甲弹，下一次发射生效</span></div><div><kbd>3</kbd><span>岛风鱼雷，再按切换宽 / 窄扇面</span></div><div><kbd>X</kbd><span>切换锁定目标，视角由鼠标控制</span></div><div><kbd>Z</kbd><span>切换跟随己方炮弹的镜头</span></div><div><kbd>R</kbd><span>损害管制，扑灭火灾、停止进水</span></div><div><kbd>T</kbd><span>战列舰维修；岛风释放烟幕</span></div><div><kbd>Y</kbd><span>侦察机 / 俾斯麦水听 / 岛风增压</span></div><div><kbd>P</kbd><span>开启 / 关闭自动副炮</span></div><div><kbd>M / Tab</kbd><span>展开海图 / 按住查看舰队战况</span></div><div><kbd>Esc / F1</kbd><span>暂停并释放鼠标 / 查看指南</span></div></div><div class="guide-mechanics"><section><h3>看准舷侧，再发射</h3><p>AP 穿甲弹适合敌舰侧面，正对装甲可能跳弹；命中核心区伤害更高。HE 高爆弹可以引发火灾。炮塔必须转到目标方向并完成装填；前后炮塔有独立射界。</p></section><section><h3>预判，而非追着舰尾打</h3><p>炮弹需要飞行时间。青色「＋」为目标匀速航行时的提前量参考点，将准星移至附近开火。移动鼠标直接环顾，X 切换锁定目标；锁定目标不会自动转动视角。</p></section><section><h3>占领海域，赢得对局</h3><p>驶入 A / B / C 区占领，敌我同时在圈内会暂停进度。控制区域持续加分，率先达到 1,000 分、歼灭敌舰，或时间结束时领先获胜。岛屿会阻挡炮火与视线。</p></section><section><h3>活下来，才有下一轮齐射</h3><p>火灾和进水持续造成伤害，用 R 处理。T 维修能恢复部分损伤，核心区损伤可恢复量较少。烟幕降低被发现的机会；开炮会暴露位置。消耗品有次数与冷却限制。</p></section></div><p class="guide-note">本作是单人对战 AI 的独立海战游戏，并非《战舰世界》官方产品。舰艇为 3D 近似模型；射程显示、航速、装填、弹道与损伤按浏览器对局节奏调整，未包含航母、潜艇、联网多人和完整装甲分区系统。操作参考 <a href="https://wiki.worldofwarships.com/Ship:Controls" target="_blank" rel="noopener">官方操作指南</a>，机制参考 <a href="https://wiki.worldofwarships.com/Ship:Ammo" target="_blank" rel="noopener">弹药规则</a>。</p>`;
window.addEventListener('keydown',e=>{if(!game&&e.key==='F1'){e.preventDefault();$('#guide-dialog').showModal();}});
const api=document.modelContext;if(api?.registerTool){const life=new AbortController();for(const tool of [{name:'read_naval_battle',title:'查看海战状态',description:'读取当前舰船选择或正在进行的战斗状态。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>game?{state:'battle',ship:game.player.spec.name,hp:Math.round(game.player.hp),seconds:Math.round(game.seconds),score:game.score.map(Math.floor),damage:Math.round(game.damage)}:{state:'port',ship:selected}},{name:'select_naval_ship',title:'选择出击舰船',description:'在母港选择舰船，不开始战斗。',inputSchema:{type:'object',properties:{ship:{type:'string',enum:Object.keys(SHIPS)}},required:['ship'],additionalProperties:false},annotations:{readOnlyHint:false},execute:({ship})=>{if(!Object.hasOwn(SHIPS,ship))throw new Error('未知舰船');if(game)throw new Error('请先返回母港');selectShip(ship);return{selected:ship,name:SHIPS[ship].name};}}]){Promise.resolve(api.registerTool(tool,{signal:life.signal})).catch(e=>console.warn('WebMCP registration:',e.message));}window.addEventListener('pagehide',()=>life.abort(),{once:true});}
$('#battle-btn').onclick=()=>{drag=false;scene.remove(portShip);$('#port').hidden=true;document.body.classList.add('in-battle');game=new Battle({scene,camera,renderer,water,islands,selected,onExit:()=>{game.dispose();game=null;scene.add(portShip);$('#port').hidden=false;document.body.classList.remove('in-battle');$('#battle-ui').hidden=true;camera.fov=45;camera.updateProjectionMatrix();}});camera.fov=50;game.updateCamera(1);game.startMouseLook();};
selectShip(selected);
